# ---------------------------------------------------------------------------
# The public edge: CloudFront, or the load balancer directly
# ---------------------------------------------------------------------------
# Azure Container Apps hands every app a free `*.azurecontainerapps.io`
# hostname WITH a managed certificate. AWS has no equivalent, and this tree
# assumed the gap away: `app_domain` and a certificate were required inputs,
# so nothing could be applied at all without first buying a domain.
#
# CloudFront closes it. Every distribution gets a `*.cloudfront.net` hostname
# covered by AWS's own certificate, at no charge and with nothing to validate,
# because AWS owns that domain. Put the distribution in front of the load
# balancer and the platform is reachable over real HTTPS with no domain, no
# ACM certificate and no DNS.
#
# WHAT IT COSTS. Requests and data transfer out are billed (there is a free
# tier; check the console for its current terms rather than trusting a number
# written here). PriceClass_100 keeps it to North America and Europe, which is
# both the cheapest tier and where the users are.
#
# WHAT YOU GIVE UP. A `*.cloudfront.net` address is fine for a pre-launch
# platform and wrong for a customer-facing one -- it is unbrandable, it is
# obviously a placeholder, and it is on the Public Suffix List, so a cookie
# can never be scoped wider than the exact host. Nothing here depends on a
# wider cookie (SESSION_DOMAIN is unset, which makes the session cookie
# host-only), but a future subdomain split would need a real domain.
#
# Switch to `edge = "alb"` the day a domain exists and dns.tf takes over.

variable "edge" {
  description = <<-EOT
    Where TLS terminates and what the public hostname is.

    "cloudfront" (default) needs NOTHING bought or configured: the
    distribution's own `*.cloudfront.net` name and AWS's certificate. The load
    balancer then listens on plain HTTP, reachable only from CloudFront.

    "alb" is the load balancer directly on 443 with a certificate for
    `app_domain`, issued by dns.tf or supplied as `acm_certificate_arn`. It
    requires a domain. This is the mode to be in once one exists.
  EOT
  type        = string
  default     = "cloudfront"

  validation {
    condition     = contains(["cloudfront", "alb"], var.edge)
    error_message = "edge must be \"cloudfront\" or \"alb\"."
  }
}

variable "cloudfront_price_class" {
  description = <<-EOT
    PriceClass_100 is North America and Europe only, and the cheapest. The
    wider classes add Asia, South America and Oceania edge locations, which
    cost more per request and buy latency nobody here is paying for yet.
  EOT
  type        = string
  default     = "PriceClass_100"

  validation {
    condition     = contains(["PriceClass_100", "PriceClass_200", "PriceClass_All"], var.cloudfront_price_class)
    error_message = "cloudfront_price_class must be PriceClass_100, PriceClass_200 or PriceClass_All."
  }
}

variable "cloudfront_origin_secret" {
  description = <<-EOT
    A shared secret CloudFront sends to the load balancer, which refuses any
    request without it.

    WHY THIS IS NOT PARANOIA. The load balancer's security group is locked to
    the `com.amazonaws.global.cloudfront.origin-facing` prefix list, which is
    every CloudFront edge on Earth -- not just this distribution. Any AWS
    customer who learns the load balancer's hostname can point THEIR
    distribution at it and serve this application under a domain they control.
    Authentication still applies, so it is not a data breach; it is a
    ready-made phishing front wearing the real login page.

    Empty (the default) leaves that gap open and the deployment working. Set
    it and the gap closes: `openssl rand -hex 32`, then pass it here.
    aws-preflight.sh A-14 reports it as unset rather than blocking, because an
    empty value is a real choice for a platform with no users yet.

    NOT generated by Terraform on purpose. A `random_password` resource would
    put the value in the state file in plaintext, which is the thing
    bootstrap-state.sh's encryption and versioning exist to contain rather
    than something to add to.
  EOT
  type        = string
  default     = ""
  sensitive   = true
}

locals {
  cf       = var.edge == "cloudfront" ? 1 : 0
  alb_edge = var.edge == "alb" ? 1 : 0

  # The hostname the browser actually uses. In CloudFront mode it is not known
  # until the distribution exists, which is why APP_URL and the Reverb origin
  # allowlist read this rather than var.app_domain.
  public_host = var.edge == "cloudfront" ? one(aws_cloudfront_distribution.this[*].domain_name) : var.app_domain
  public_url  = "https://${local.public_host}"
}

# Managed policies, by name rather than by the well-known ID, so a typo is a
# plan-time lookup failure instead of a distribution that silently caches
# authenticated pages.
data "aws_cloudfront_cache_policy" "disabled" {
  count = local.cf
  name  = "Managed-CachingDisabled"
}

# Forwards every viewer header, cookie and query string to the origin. Correct
# here for two reasons: this is an application, not a CDN -- caching a
# logged-in Inertia page and serving it to the next visitor would be a
# workspace data leak -- and the WebSocket upgrade handshake needs the
# Connection and Upgrade headers to reach Reverb intact.
data "aws_cloudfront_origin_request_policy" "all_viewer" {
  count = local.cf
  name  = "Managed-AllViewer"
}

resource "aws_cloudfront_distribution" "this" {
  count = local.cf * local.on

  enabled         = true
  comment         = "${local.name} public edge"
  price_class     = var.cloudfront_price_class
  is_ipv6_enabled = true

  origin {
    domain_name = aws_lb.this[0].dns_name
    origin_id   = "alb"

    custom_origin_config {
      http_port  = 80
      https_port = 443
      # HTTP to the origin because the load balancer has no certificate in
      # this mode -- it has no domain to have one for. The hop is inside the
      # VPC's public subnets rather than across the internet, and the load
      # balancer accepts nothing but CloudFront.
      origin_protocol_policy = "http-only"
      origin_ssl_protocols   = ["TLSv1.2"]
      # Reverb holds WebSockets open; the ALB's own idle_timeout is 300 for
      # the same reason. 60 is CloudFront's maximum for a read timeout on a
      # custom origin, and the WebSocket itself is not subject to it once
      # upgraded.
      origin_read_timeout      = 60
      origin_keepalive_timeout = 60
    }

    dynamic "custom_header" {
      for_each = var.cloudfront_origin_secret != "" ? [1] : []
      content {
        name  = "X-Origin-Verify"
        value = var.cloudfront_origin_secret
      }
    }
  }

  default_cache_behavior {
    target_origin_id       = "alb"
    viewer_protocol_policy = "redirect-to-https"
    allowed_methods        = ["GET", "HEAD", "OPTIONS", "PUT", "POST", "PATCH", "DELETE"]
    cached_methods         = ["GET", "HEAD"]
    compress               = true

    cache_policy_id          = data.aws_cloudfront_cache_policy.disabled[0].id
    origin_request_policy_id = data.aws_cloudfront_origin_request_policy.all_viewer[0].id
  }

  viewer_certificate {
    # AWS's own certificate for *.cloudfront.net. This is the whole point of
    # the mode: a browser-trusted certificate with no domain to own and
    # nothing to renew.
    cloudfront_default_certificate = true
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  tags = var.tags
}
