# ---------------------------------------------------------------------------
# The public edge: CloudFront, or the load balancer directly
# ---------------------------------------------------------------------------
# Azure Container Apps hands every app a free `*.azurecontainerapps.io`
# hostname WITH a managed certificate. AWS has no equivalent, and this tree
# assumed the gap away: `app_domain` and a certificate were required inputs,
# so nothing could be applied at all without first buying a domain.
#
# CloudFront closes it. Every distribution gets a `*.cloudfront.net` hostname
# covered by AWS's own certificate, at no charge and with nothing to validate,
# because AWS owns that domain. Put the distribution in front of the load
# balancer and the platform is reachable over real HTTPS with no domain, no
# ACM certificate and no DNS.
#
# WHAT IT COSTS. Requests and data transfer out are billed (there is a free
# tier; check the console for its current terms rather than trusting a number
# written here). PriceClass_100 keeps it to North America and Europe, which is
# both the cheapest tier and where the users are.
#
# WHAT YOU GIVE UP. A `*.cloudfront.net` address is fine for a pre-launch
# platform and wrong for a customer-facing one -- it is unbrandable, it is
# obviously a placeholder, and it is on the Public Suffix List, so a cookie
# can never be scoped wider than the exact host. Nothing here depends on a
# wider cookie (SESSION_DOMAIN is unset, which makes the session cookie
# host-only), but a future subdomain split would need a real domain.
#
# The hostname is also NOT STABLE across a power cycle. The distribution is
# gated on `local.on` (it bills per request and per GB for as long as it
# exists), so `power = "off"` destroys it and the next power-on mints a
# different *.cloudfront.net name -- which then lands in APP_URL,
# REVERB_ALLOWED_ORIGINS and Hatchet's cookie domain, and invalidates every
# link anybody saved. Expect the cycle to take considerably longer than the
# fifteen minutes the nightly sweeps need, too: disabling and deleting a
# distribution is a propagation, not an API call, and `wait_for_deployment`
# defaults to true. The nightly sweeps do not touch it -- they scale ECS and
# stop RDS -- so this is a `power = "off"` concern only.
#
# Switch to `edge = "alb"` the day a domain exists and dns.tf takes over.

variable "edge" {
  description = <<-EOT
    Where TLS terminates and what the public hostname is.

    "cloudfront" (default) needs NOTHING bought or configured: the
    distribution's own `*.cloudfront.net` name and AWS's certificate. The load
    balancer then listens on plain HTTP, reachable only from CloudFront.

    "alb" is the load balancer directly on 443 with a certificate for
    `app_domain`, issued by dns.tf or supplied as `acm_certificate_arn`. It
    requires a domain. This is the mode to be in once one exists.
  EOT
  type        = string
  default     = "cloudfront"

  validation {
    condition     = contains(["cloudfront", "alb"], var.edge)
    error_message = "edge must be \"cloudfront\" or \"alb\"."
  }
}

variable "cloudfront_price_class" {
  description = <<-EOT
    PriceClass_100 is North America and Europe only, and the cheapest. The
    wider classes add Asia, South America and Oceania edge locations, which
    cost more per request and buy latency nobody here is paying for yet.
  EOT
  type        = string
  default     = "PriceClass_100"

  validation {
    condition     = contains(["PriceClass_100", "PriceClass_200", "PriceClass_All"], var.cloudfront_price_class)
    error_message = "cloudfront_price_class must be PriceClass_100, PriceClass_200 or PriceClass_All."
  }
}

variable "cloudfront_origin_secret" {
  description = <<-EOT
    A shared secret CloudFront sends to the load balancer, which refuses any
    request without it.

    WHY THIS IS NOT PARANOIA. The load balancer's security group is locked to
    the `com.amazonaws.global.cloudfront.origin-facing` prefix list, which is
    every CloudFront edge on Earth -- not just this distribution. Any AWS
    customer who learns the load balancer's hostname can point THEIR
    distribution at it and serve this application under a domain they control.
    Authentication still applies, so it is not a data breach; it is a
    ready-made phishing front wearing the real login page.

    Empty (the default) leaves that gap open and the deployment working. Set
    it and the gap closes: `openssl rand -hex 32`, then pass it here.
    aws-preflight.sh A-14 reports it as unset rather than blocking, because an
    empty value is a real choice for a platform with no users yet.

    NOT generated by Terraform on purpose. A `random_password` resource would
    put the value in the state file in plaintext, which is the thing
    bootstrap-state.sh's encryption and versioning exist to contain rather
    than something to add to.
  EOT
  type        = string
  default     = ""
  sensitive   = true
}

locals {
  cf       = var.edge == "cloudfront" ? 1 : 0
  alb_edge = var.edge == "alb" ? 1 : 0

  # The hostname the browser actually uses. In CloudFront mode it is not known
  # until the distribution exists, which is why APP_URL and the Reverb origin
  # allowlist read this rather than var.app_domain.
  #
  # The null guard is not decoration. The distribution is gated on local.on, so
  # with `power = "off"` its count is zero and `one([])` is null — and Terraform
  # refuses to put a null in a string template ("Invalid template interpolation
  # value"). Locals are evaluated whether or not the resources referencing them
  # expand, so without this the ENTIRE plan fails in the default edge mode the
  # moment the power flag is turned off, which is the one state it exists for.
  # An unknown value (the first apply, before the distribution exists) passes
  # through the conditional as unknown and lands as "known after apply".
  _cf_host    = one(aws_cloudfront_distribution.this[*].domain_name)
  public_host = var.edge == "cloudfront" ? (local._cf_host == null ? "" : local._cf_host) : var.app_domain
  public_url  = "https://${local.public_host}"
}

# Managed policies, by name rather than by the well-known ID, so a typo is a
# plan-time lookup failure instead of a distribution that silently caches
# authenticated pages.
data "aws_cloudfront_cache_policy" "disabled" {
  count = local.cf
  name  = "Managed-CachingDisabled"
}

# Forwards every viewer header, cookie and query string to the origin. Correct
# here for two reasons: this is an application, not a CDN -- caching a
# logged-in Inertia page and serving it to the next visitor would be a
# workspace data leak -- and the WebSocket upgrade handshake needs the
# Connection and Upgrade headers to reach Reverb intact.
data "aws_cloudfront_origin_request_policy" "all_viewer" {
  count = local.cf
  name  = "Managed-AllViewer"
}

resource "aws_cloudfront_distribution" "this" {
  count = local.cf * local.on

  enabled         = true
  comment         = "${local.name} public edge"
  price_class     = var.cloudfront_price_class
  is_ipv6_enabled = true

  origin {
    domain_name = aws_lb.this[0].dns_name
    origin_id   = "alb"

    custom_origin_config {
      http_port  = 80
      https_port = 443
      # HTTP to the origin because the load balancer has no certificate in
      # this mode -- it has no domain to have one for, and CloudFront will not
      # speak HTTPS to an origin presenting an untrusted one.
      #
      # BE HONEST ABOUT WHAT THIS COSTS. A CloudFront edge is NOT inside this
      # VPC: the edge-to-origin hop crosses the public internet, so on this
      # leg every session cookie, every uploaded byte and every answer travels
      # in cleartext. The security group narrows WHO may open that connection;
      # it does not encrypt it. The only fix is a domain and a certificate on
      # the load balancer, which is `edge = "alb"`. Until then, treat this mode
      # as pre-launch only -- which is the same conclusion the *.cloudfront.net
      # hostname forces for its own reasons.
      origin_protocol_policy = "http-only"
      origin_ssl_protocols   = ["TLSv1.2"]
      # Reverb holds WebSockets open; the ALB's own idle_timeout is 300 for
      # the same reason. 60 is CloudFront's maximum for a read timeout on a
      # custom origin without a quota increase, and the WebSocket itself is not
      # subject to it once upgraded. It IS a ceiling on ordinary requests,
      # though: GEORAG_MAX_UPLOAD_BYTES admits 512 MB through the Laravel web
      # tier, and any upload whose response takes longer than 60s to begin
      # becomes a CloudFront 504 that the load balancer never saw a reason for.
      origin_read_timeout      = 60
      origin_keepalive_timeout = 60
    }

    dynamic "custom_header" {
      for_each = var.cloudfront_origin_secret != "" ? [1] : []
      content {
        name  = "X-Origin-Verify"
        value = var.cloudfront_origin_secret
      }
    }
  }

  default_cache_behavior {
    target_origin_id       = "alb"
    viewer_protocol_policy = "redirect-to-https"
    allowed_methods        = ["GET", "HEAD", "OPTIONS", "PUT", "POST", "PATCH", "DELETE"]
    cached_methods         = ["GET", "HEAD"]
    compress               = true

    cache_policy_id          = data.aws_cloudfront_cache_policy.disabled[0].id
    origin_request_policy_id = data.aws_cloudfront_origin_request_policy.all_viewer[0].id
  }

  viewer_certificate {
    # AWS's own certificate for *.cloudfront.net. This is the whole point of
    # the mode: a browser-trusted certificate with no domain to own and
    # nothing to renew.
    #
    # It also PINS the TLS floor, and downwards. CloudFront forces
    # minimum_protocol_version to TLSv1 for the default certificate and
    # refuses to let it be set -- the security-policy knob only exists for a
    # certificate you bring. `edge = "alb"` serves
    # ELBSecurityPolicy-TLS13-1-2-2021-06, so switching modes moves the floor
    # from TLS 1.2 to TLS 1.0 without saying so anywhere else. One more thing
    # that is fine before launch and wrong in front of a customer.
    cloudfront_default_certificate = true
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  tags = var.tags

  lifecycle {
    # `app_domain` is INERT in this mode: dns.tf is skipped entirely, no
    # certificate is issued, no Route 53 record is written, and the browser
    # reaches a *.cloudfront.net name instead. Since `edge` now defaults to
    # "cloudfront", an operator who supplies app_domain the way every version
    # of this tree before 2026-09-16 required would otherwise get silence --
    # and an existing `edge = "alb"` deployment that re-applies without
    # setting `edge` would be migrated off its own domain, destroying the
    # HTTPS listener, the ACM certificate and the alias record on the way.
    precondition {
      condition     = var.app_domain == ""
      error_message = "app_domain is set but edge is \"cloudfront\", which serves the distribution's own *.cloudfront.net name and ignores app_domain, DNS and ACM completely. Set edge = \"alb\" to serve that domain, or clear app_domain to say the CloudFront hostname is intended."
    }
  }
}
