#!/usr/bin/env bash
# init-backend.sh — one-command path from "no backend configured" to
# `terraform init` against a real S3 bucket, for whichever AWS account the
# caller's credentials point at.
#
#   bash deploy/aws/terraform/init-backend.sh [bucket] [region]
#
# Why this exists: backend.tf is a deliberately PARTIAL S3 backend config —
# S3 bucket names are globally unique and Terraform's `backend` block cannot
# use variables/interpolation, so no single literal bucket name is correct
# for every deployer's AWS account (staging vs prod, or two different
# operators, would collide or fight over one hardcoded name). Someone has to
# resolve an actual bucket name from an actual account before init can run.
# This script does that resolution instead of asking the operator to guess
# or transcribe an account ID by hand.
#
# What it does, in order:
#   1. Confirms `aws` is installed and credentials actually work.
#   2. Derives a deterministic bucket name from the caller's account ID
#      (georag-tfstate-<account-id>), unless overridden.
#   3. Shells out to bootstrap-state.sh to create/verify that bucket
#      (versioning, encryption, public-access-block, TLS-only policy,
#      lifecycle) — this script does not duplicate that logic.
#   4. Writes backend.hcl (gitignored) with the resolved bucket/region.
#   5. Runs `terraform init -backend-config=backend.hcl -reconfigure`.
#
# Idempotent: safe to re-run. Re-running with the same account just verifies
# the bucket and re-inits; the bucket name is deterministic so nothing new
# gets created on repeat runs.
#
# Override the bucket name explicitly if you want one you chose yourself
# instead of the auto-generated georag-tfstate-<account-id> (e.g. to share
# one bucket/prefix scheme across environments, or to match an existing
# naming convention):
#
#   bash deploy/aws/terraform/init-backend.sh my-own-bucket-name us-east-1
#   TFSTATE_BUCKET=my-own-bucket-name bash deploy/aws/terraform/init-backend.sh
#
# For that case — naming the bucket yourself rather than accepting the
# auto-generated name — you can also skip this script entirely and follow
# the manual path in backend.hcl.example.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

command -v aws >/dev/null 2>&1 || { echo "aws CLI not found" >&2; exit 1; }
command -v terraform >/dev/null 2>&1 || { echo "terraform not found" >&2; exit 1; }

ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text 2>/dev/null)" || {
  echo "error: 'aws sts get-caller-identity' failed — no working AWS credentials." >&2
  echo "       configure credentials (aws configure / env vars / SSO login) and retry." >&2
  exit 1
}

BUCKET="${1:-${TFSTATE_BUCKET:-georag-tfstate-${ACCOUNT_ID}}}"
REGION="${2:-${TFSTATE_REGION:-us-east-1}}"

echo "account: $(aws sts get-caller-identity --query Arn --output text)"
echo "bucket:  ${BUCKET}  (${REGION})"
echo

echo "== bootstrap-state.sh =="
# Already cd'd to this script's own directory above, so bootstrap-state.sh is
# a plain sibling from here. Re-deriving the directory from BASH_SOURCE again
# (as an earlier version of this script did) double-joins it onto the cwd we
# just changed into (deploy/aws/terraform/deploy/aws/terraform/...) and fails
# with "No such file or directory" — BASH_SOURCE doesn't change when you cd.
bash ./bootstrap-state.sh "$BUCKET" "$REGION"
echo

echo "== writing backend.hcl =="
cat > backend.hcl <<EOF
# Generated by init-backend.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) — not committed (see .gitignore).
# Re-run init-backend.sh to regenerate; do not hand-edit unless you know why.
bucket = "${BUCKET}"
region = "${REGION}"
EOF
echo "wrote backend.hcl"
echo

echo "== terraform init =="
terraform init -backend-config=backend.hcl -reconfigure
