"""Surpac: what the reader skipped or dropped reaches the caller; a one-vertex string is a point.

GIS audit 2026-10, findings 7 and 8.

Finding 7. ``read_surpac_strings`` skipped malformed vertices, discarded the
descriptor fields and noticed a missing END record, and said so only in the
log, so an upload that had lost vertices (or whole strings, if the file was cut
short) looked identical to a clean one. The counts and the END flag now sit on
``SurpacFile`` and the spatial layer turns them into warnings.

Finding 8. A string with one distinct vertex became ``LINESTRING(x y)``, which
is not valid WKT (PostGIS: "geometry requires more points"); the whole file
goes in one INSERT, so one such string failed the upload.
"""
from pathlib import Path

from shapely import wkt as shapely_wkt

from georag_geoparsers.spatial_parser import parse_spatial_file
from georag_geoparsers.surpac_parser import MAX_DESCRIPTORS_PER_STRING, read_surpac_strings

TITLE = "synthetic.str,,Generated by test,"
AXIS = "0,0.000,0.000,0.000,0.000,1.000,0.000"
TERMINATOR = "0,0.000,0.000,0.000"
END = "0,0.000,0.000,0.000,END"

#: NAD83 / UTM zone 4N, where the Shumagin delivery sits.
UTM_4N = 26904

#: A well-formed square (closed ring) at one level.
SQUARE = [
    "1,6120000.0,399000.0,10.0,",
    "1,6120010.0,399000.0,10.0,",
    "1,6120010.0,399010.0,10.0,",
    "1,6120000.0,399000.0,10.0,",
    TERMINATOR,
]


def write_str(tmp_path: Path, body: list[str]) -> Path:
    path = tmp_path / "synthetic.str"
    path.write_bytes(("\r\n".join([TITLE, AXIS, *body]) + "\r\n").encode("utf-8"))
    return path


def codes(result) -> list[str]:
    return [w["code"] for w in result.warnings]


# ---------------------------------------------------------------------------
# The reader
# ---------------------------------------------------------------------------
class TestSurpacFileCarriesWhatItSkipped:
    def test_a_clean_file_reports_nothing(self, tmp_path: Path) -> None:
        parsed = read_surpac_strings(write_str(tmp_path, [*SQUARE, END]))
        assert (parsed.rows_skipped, parsed.descriptor_rows, parsed.descriptors_dropped) == (0, 0, 0)
        assert parsed.truncated is False

    def test_skipped_rows_are_counted(self, tmp_path: Path) -> None:
        parsed = read_surpac_strings(
            write_str(
                tmp_path,
                [
                    "1,6120000.0,399000.0,10.0,",
                    "1,6120001.0,NORTHING,10.0,",   # non-numeric
                    "1,6120002.0,399002.0,",        # Z missing
                    "not a record at all",
                    "1,6120003.0,399003.0,10.0,",
                    TERMINATOR,
                    END,
                ],
            ),
        )
        assert parsed.rows_skipped == 3
        assert len(parsed.strings[0].points) == 2

    def test_a_missing_end_record_is_truncated(self, tmp_path: Path) -> None:
        assert read_surpac_strings(write_str(tmp_path, [*SQUARE])).truncated is True

    def test_a_file_that_stops_inside_a_string_is_truncated_and_keeps_its_vertices(self, tmp_path: Path) -> None:
        parsed = read_surpac_strings(write_str(tmp_path, ["1,6120000.0,399000.0,10.0,", "1,6120010.0,399000.0,10.0,"]))
        assert parsed.truncated is True
        assert len(parsed.strings) == 1 and len(parsed.strings[0].points) == 2

    def test_the_end_record_means_complete(self, tmp_path: Path) -> None:
        assert read_surpac_strings(write_str(tmp_path, [*SQUARE, END])).truncated is False

    def test_descriptors_are_kept_per_string_distinct_and_in_order(self, tmp_path: Path) -> None:
        parsed = read_surpac_strings(
            write_str(
                tmp_path,
                [
                    "1,6120000.0,399000.0,10.0,ORE",
                    "1,6120001.0,399001.0,10.0,HW,3",
                    "1,6120002.0,399002.0,10.0,ORE",
                    "1,6120003.0,399003.0,10.0,",
                    TERMINATOR,
                    "2,6120010.0,399010.0,12.0,FW",
                    TERMINATOR,
                    END,
                ],
            ),
        )
        assert parsed.strings[0].descriptors == ("ORE", "HW,3")
        assert parsed.strings[1].descriptors == ("FW",)
        assert parsed.descriptor_rows == 4
        assert parsed.descriptors_dropped == 0

    def test_descriptors_beyond_the_cap_are_counted_not_lost_silently(self, tmp_path: Path) -> None:
        n = MAX_DESCRIPTORS_PER_STRING + 7
        rows = [f"1,{6120000 + i}.0,399000.0,10.0,P{i}" for i in range(n)]
        parsed = read_surpac_strings(write_str(tmp_path, [*rows, TERMINATOR, END]))
        assert len(parsed.strings[0].descriptors) == MAX_DESCRIPTORS_PER_STRING
        assert parsed.strings[0].descriptors_dropped == 7
        assert parsed.descriptors_dropped == 7


# ---------------------------------------------------------------------------
# Through parse_spatial_file: warnings the caller can show
# ---------------------------------------------------------------------------
class TestWarningsReachTheSpatialResult:
    def test_a_clean_file_with_a_crs_has_no_warnings(self, tmp_path: Path) -> None:
        result = parse_spatial_file(str(write_str(tmp_path, [*SQUARE, END])), source_epsg=UTM_4N)
        assert result.warnings == []

    def test_skipped_rows_become_a_warning_with_the_count(self, tmp_path: Path) -> None:
        path = write_str(tmp_path, ["1,6120000.0,399000.0,10.0,", "1,oops,399001.0,10.0,", TERMINATOR, END])
        result = parse_spatial_file(str(path), source_epsg=UTM_4N)
        (w,) = [w for w in result.warnings if w["code"] == "surpac_rows_skipped"]
        assert w["context"] == {"rows_skipped": 1}
        assert "1 record(s)" in w["message"]
        assert result.feature_count == 1, "the string that survives is still imported"

    def test_a_truncated_file_becomes_a_warning(self, tmp_path: Path) -> None:
        result = parse_spatial_file(str(write_str(tmp_path, [*SQUARE])), source_epsg=UTM_4N)
        (w,) = [w for w in result.warnings if w["code"] == "surpac_truncated"]
        assert "END" in w["message"]
        assert w["context"] == {"strings_read": 1}

    def test_a_file_with_an_end_record_is_not_called_truncated(self, tmp_path: Path) -> None:
        result = parse_spatial_file(str(write_str(tmp_path, [*SQUARE, END])), source_epsg=UTM_4N)
        assert "surpac_truncated" not in codes(result)

    def test_descriptors_overflow_becomes_a_warning(self, tmp_path: Path) -> None:
        rows = [f"1,{6120000 + i}.0,399000.0,10.0,P{i}" for i in range(MAX_DESCRIPTORS_PER_STRING + 3)]
        result = parse_spatial_file(str(write_str(tmp_path, [*rows, TERMINATOR, END])), source_epsg=UTM_4N)
        (w,) = [w for w in result.warnings if w["code"] == "surpac_descriptors_dropped"]
        assert w["context"] == {"descriptors_dropped": 3}

    def test_the_no_crs_warning_is_still_there_and_the_new_ones_sit_beside_it(self, tmp_path: Path) -> None:
        result = parse_spatial_file(str(write_str(tmp_path, [*SQUARE])))
        assert set(codes(result)) == {"surpac_no_crs", "surpac_truncated"}
        assert result.crs_missing is True


class TestDescriptorsSurviveInProperties:
    def test_they_are_on_the_feature(self, tmp_path: Path) -> None:
        path = write_str(tmp_path, ["1,6120000.0,399000.0,10.0,ORE", "1,6120001.0,399001.0,10.0,ORE,HW", TERMINATOR, END])
        (feature,) = parse_spatial_file(str(path), source_epsg=UTM_4N).features
        assert feature.properties["surpac_descriptors"] == ["ORE", "ORE,HW"]

    def test_a_string_with_none_has_no_such_key(self, tmp_path: Path) -> None:
        (feature,) = parse_spatial_file(str(write_str(tmp_path, [*SQUARE, END])), source_epsg=UTM_4N).features
        assert "surpac_descriptors" not in feature.properties


# ---------------------------------------------------------------------------
# Finding 8: one distinct vertex is a point
# ---------------------------------------------------------------------------
class TestOneVertexStrings:
    def _features(self, tmp_path: Path, body: list[str]):
        return parse_spatial_file(str(write_str(tmp_path, body)), source_epsg=UTM_4N).features

    def test_a_single_vertex_is_a_point(self, tmp_path: Path) -> None:
        (feature,) = self._features(tmp_path, ["1,6120684.0,399183.0,125.0,", TERMINATOR, END])
        assert feature.geometry_type == "Point"
        geom = shapely_wkt.loads(feature.geometry_wkt)
        assert geom.geom_type == "Point" and geom.is_valid
        # Still reprojected: Shumagin Island is near 160.6 W, 55.2 N.
        assert -161.0 < geom.x < -160.0 and 55.0 < geom.y < 55.5

    def test_the_same_vertex_repeated_is_a_point_too(self, tmp_path: Path) -> None:
        row = "1,6120684.0,399183.0,125.0,"
        (feature,) = self._features(tmp_path, [row, row, row, TERMINATOR, END])
        assert feature.geometry_type == "Point"
        assert feature.properties["point_count"] == 3 and feature.properties["closed"] is True

    def test_no_feature_is_ever_an_invalid_linestring(self, tmp_path: Path) -> None:
        body = [
            "1,6120000.0,399000.0,10.0,", TERMINATOR,                                  # 1 vertex
            "2,6120000.0,399000.0,10.0,", "2,6120000.0,399000.0,10.0,", TERMINATOR,   # 2 identical
            "3,6120000.0,399000.0,10.0,", "3,6120010.0,399000.0,10.0,", TERMINATOR,   # a real line
            END,
        ]
        for feature in self._features(tmp_path, body):
            geom = shapely_wkt.loads(feature.geometry_wkt)
            assert geom.is_valid, f"{feature.name}: {feature.geometry_wkt}"
            if geom.geom_type == "LineString":
                assert len(geom.coords) >= 2 and geom.length > 0

    def test_lines_and_rings_are_unchanged(self, tmp_path: Path) -> None:
        line, ring = (
            self._features(tmp_path, ["1,6120000.0,399000.0,10.0,", "1,6120010.0,399000.0,10.0,", TERMINATOR, END])[0],
            self._features(tmp_path, [*SQUARE, END])[0],
        )
        assert (line.geometry_type, ring.geometry_type) == ("LineString", "Polygon")

    def test_a_degenerate_ring_of_two_distinct_vertices_is_still_a_line(self, tmp_path: Path) -> None:
        body = ["1,6120000.0,399000.0,10.0,", "1,6120010.0,399000.0,10.0,", "1,6120000.0,399000.0,10.0,", TERMINATOR, END]
        (feature,) = self._features(tmp_path, body)
        assert feature.geometry_type == "LineString"

    def test_feature_count_equals_string_count(self, tmp_path: Path) -> None:
        body = ["1,6120000.0,399000.0,10.0,", TERMINATOR, *SQUARE[:-1], TERMINATOR, END]
        result = parse_spatial_file(str(write_str(tmp_path, body)), source_epsg=UTM_4N)
        assert result.feature_count == 2 == len(result.features)


def test_the_reader_still_claims_no_crs() -> None:
    """The existing contract: no field of the new surface mentions a CRS."""
    import dataclasses

    from georag_geoparsers.surpac_parser import SurpacFile, SurpacString

    names = {f.name.lower() for cls in (SurpacFile, SurpacString) for f in dataclasses.fields(cls)}
    assert not any("crs" in n or "epsg" in n or "srid" in n for n in names)
    assert {"rows_skipped", "truncated", "descriptor_rows", "descriptors_dropped"} <= names
