"""Regression guard for the MapInfo binary-in-character decode.

Every number in this file was measured by hand against the RedStar delivery on
2026-08-24, not generated by the code under test. That matters more here than
in most parsers: the failure this module exists to prevent is silent. GDAL does
not error on these tables, it returns them 91.9% null, and a decode rule that
drifted would go on returning plausible-looking floats. The pinned values are
the only thing that would notice.

The four target files were chosen to cover the two ways the naive
"non-printable means binary" test fails, plus the two ways it must not fire:

* Sitka_trD.DAT       — binary doubles AND a width-4 binary int32
* soils                — the printable-bytes trap (cu_ppm) and the
                         trailing-NUL trap (samsubtype) in one table
* MiscPoints_2005.dbf  — ordinary ASCII dBASE, the no-regression guard
* alteration_riehle.dbf — ASCII dBASE with real decimals
"""

import struct
from pathlib import Path

import pytest

from georag_geoparsers.dbase_reader import DbaseTable, read_dbase

REDSTAR = Path("C:/Users/GeoRAG/Desktop/RedStar")

SITKA_TRENCH = REDSTAR / "Apollo Sitka" / "Trench" / "Sitka_tr" / "Sitka_trD.DAT"
SITKA_LEGEND = REDSTAR / "Apollo Sitka" / "Trench" / "Sitka_tr" / "Sitka_tr_Legend.DAT"
SOILS = (
    REDSTAR / "Apollo Sitka" / "Workspaces" / "ApolloSitka_2D"
    / "Sitka_CMap_12.6.2015" / "all_historical_soils_clean.DAT"
)
MISC_POINTS = REDSTAR / "Unga Regional (inc)" / "Geology" / "2005" / "MiscPoints_2005.dbf"
ALTERATION = REDSTAR / "Unga Regional (inc)" / "Geology" / "Digital Data" / "alteration_riehle.dbf"

pytestmark = pytest.mark.skipif(
    not REDSTAR.is_dir(),
    reason="RedStar delivery not mounted on this machine",
)


def _field(table: DbaseTable, name: str):
    return next(f for f in table.fields if f.name == name)


def _column(table: DbaseTable, name: str) -> list:
    return [row[name] for row in table.rows]


@pytest.fixture(scope="module")
def sitka() -> DbaseTable:
    return read_dbase(SITKA_TRENCH)


@pytest.fixture(scope="module")
def soils() -> DbaseTable:
    return read_dbase(SOILS)


@pytest.fixture(scope="module")
def misc_points() -> DbaseTable:
    return read_dbase(MISC_POINTS)


# ---------------------------------------------------------------------------
# Sitka_trD.DAT — binary doubles plus a width-4 binary int32
# ---------------------------------------------------------------------------

def test_sitka_shape(sitka: DbaseTable) -> None:
    assert sitka.record_count == 10
    assert sitka.deleted_count == 0
    assert len(sitka.rows) == 10
    assert len(sitka.fields) == 9


def test_sitka_declares_every_field_as_character(sitka: DbaseTable) -> None:
    """The header is useless here — all nine columns claim to be text.

    This is the premise of the whole module. If a future MapInfo export ever
    started declaring real types, the decode rule would be running on a file
    that no longer needs it and this assertion should be revisited.
    """
    assert {f.dbase_type for f in sitka.fields} == {"C"}


def test_sitka_collar_ids_are_text(sitka: DbaseTable) -> None:
    assert _field(sitka, "CollarID_D").decoded_as == "text"
    ids = _column(sitka, "CollarID_D")
    assert ids == [
        "TR002-Sitka", "TR002-Sitka",
        "TR003-Sitka", "TR003-Sitka",
        "TR004-Sitka", "TR004-Sitka",
        "TR005-Sitka", "TR005-Sitka",
        "TR006-Sitka", "TR006-Sitka",
    ]


def test_sitka_azimuths_decode_as_doubles(sitka: DbaseTable) -> None:
    assert _field(sitka, "Azimuth_DB").decoded_as == "double"
    assert _column(sitka, "Azimuth_DB") == [
        322.8, 322.8, 294.1, 294.1, 157.8, 157.8, 160.0, 160.0, 321.8, 321.8,
    ]


def test_sitka_depth_max(sitka: DbaseTable) -> None:
    depths = _column(sitka, "Depth_DB")
    assert _field(sitka, "Depth_DB").decoded_as == "double"
    assert max(depths) == 82.0
    # The zeros are measured trench-start depths, not missing values: MapInfo
    # writes 0.0 as eight NUL bytes and has no separate null encoding, so a
    # reader that treated all-NUL as absent would blank half this column.
    assert depths == [0.0, 61.5, 0.0, 32.0, 0.0, 40.0, 0.0, 19.0, 0.0, 82.0]


def test_sitka_midpoint_coordinates_are_in_the_survey_area(sitka: DbaseTable) -> None:
    """A misread double lands nowhere near UTM zone 4N — hence range pins."""
    xs = _column(sitka, "MidX_DB")
    ys = _column(sitka, "MidY_DB")
    assert min(xs) >= 400586 and max(xs) <= 400864
    assert min(ys) >= 6117146 and max(ys) <= 6117348


def test_sitka_key_is_a_width_four_int32(sitka: DbaseTable) -> None:
    """The case a range test cannot reach — width 4 is decided by refutation."""
    key = _field(sitka, "__Key_DB")
    assert key.length == 4
    assert key.dbase_type == "C"
    assert key.decoded_as == "int32"
    assert _column(sitka, "__Key_DB") == [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


def test_sitka_all_empty_columns_are_reported_as_text(sitka: DbaseTable) -> None:
    """Dip_DB and MidZ_DB are eight NUL bytes in all ten rows.

    Eight NULs is simultaneously a valid empty string and a valid 0.0, so a
    column made entirely of them carries no evidence either way and the module
    declines to guess — the documented "all-empty field reports text" rule.

    The bytes themselves are pinned below so the underlying fact survives even
    if that policy is ever revisited: the source data really is all-zero, and
    a caller that wants these as numeric zeros is making a semantic choice
    this reader deliberately does not make for it.
    """
    for name in ("Dip_DB", "MidZ_DB"):
        assert _field(sitka, name).decoded_as == "text"
        assert set(_column(sitka, name)) == {""}

    raw = SITKA_TRENCH.read_bytes()
    _count, header_len, record_len = struct.unpack("<IHH", raw[4:12])
    offsets: dict[str, int] = {}
    cursor = 1                                  # byte 0 of a record is the deletion flag
    for field in sitka.fields:
        offsets[field.name] = cursor
        cursor += field.length

    for name in ("Dip_DB", "MidZ_DB"):
        start = offsets[name]
        for row in range(10):
            cell = raw[header_len + row * record_len + start:][:8]
            assert cell == b"\x00" * 8
            assert struct.unpack("<d", cell)[0] == 0.0


# ---------------------------------------------------------------------------
# Sitka_tr_Legend.DAT — the 0x2A deleted-record flag
# ---------------------------------------------------------------------------

def test_legend_counts_deleted_records_without_returning_them() -> None:
    """23 declared, 7 delete-flagged, 16 live — all three numbers matter.

    dBASE never reclaims a deleted record's bytes, so the header total and the
    usable row count legitimately disagree. Reporting only one of them makes a
    downstream row-count reconciliation impossible to satisfy.
    """
    table = read_dbase(SITKA_LEGEND)
    assert table.record_count == 23
    assert table.deleted_count == 7
    assert len(table.rows) == 16
    assert _column(table, "ID") == list(range(7, 23))


# ---------------------------------------------------------------------------
# all_historical_soils_clean.DAT — both traps in one table
# ---------------------------------------------------------------------------

def test_soils_shape(soils: DbaseTable) -> None:
    assert soils.record_count == 854
    assert soils.deleted_count == 0
    assert len(soils.rows) == 854
    assert len(soils.fields) == 111


def test_soils_coordinate_ranges(soils: DbaseTable) -> None:
    eastings = _column(soils, "easting")
    northings = _column(soils, "northing")
    assert (min(eastings), max(eastings)) == (383954.0, 410985.0)
    assert (min(northings), max(northings)) == (6117254.0, 6129820.0)


def test_soils_printable_bytes_trap(soils: DbaseTable) -> None:
    """cu_ppm row 0 is 14.0, whose eight bytes are all printable-or-NUL.

    A printability test reads those bytes as the string ',@'. Getting 14.0
    here is the proof that classification is driven by the value's magnitude
    and not by what its bytes look like.
    """
    assert _field(soils, "cu_ppm").decoded_as == "double"
    assert _column(soils, "cu_ppm")[0] == 14.0


def test_soils_trailing_nul_trap(soils: DbaseTable) -> None:
    """samsubtype is real text whose NUL padding sits in the exponent.

    Unpacked as a double it is 6.3e-315, so a printability test hands back a
    denormal in place of a sample-type code. It must stay a string.
    """
    assert _field(soils, "samsubtype").decoded_as == "text"
    values = _column(soils, "samsubtype")
    assert values[0] == "SOIL"
    assert set(values) == {"", "SOIL", "TALU", "FROS"}


def test_soils_field_classification_tally(soils: DbaseTable) -> None:
    """37 double / 3 text / 41 all-empty across the 81 width-8 'C' fields.

    This is the measurement the decode rule was derived from, and it is the
    assertion that would catch a rule that drifted in either direction: a
    looser floor pulls the three text columns into the numeric bucket, a
    tighter window pushes real assay columns out of it.
    """
    width8 = [f for f in soils.fields if f.dbase_type == "C" and f.length == 8]
    assert len(width8) == 81

    doubles = [f.name for f in width8 if f.decoded_as == "double"]
    texts = [f.name for f in width8 if f.decoded_as == "text"]
    populated_texts = [name for name in texts if any(row[name] for row in soils.rows)]

    assert len(doubles) == 37
    assert len(texts) == 44
    assert sorted(populated_texts) == ["quality", "samsubtype", "slope"]
    assert len(texts) - len(populated_texts) == 41


def test_soils_narrow_character_fields_are_never_read_as_binary(soils: DbaseTable) -> None:
    """`color` is width 4 and holds 'BR' — the width-4 false-positive case.

    Unpacked as an int32 it is a perfectly plausible 21058, which is exactly
    why width 4 cannot be decided per cell.
    """
    assert _field(soils, "color").decoded_as == "text"
    assert _column(soils, "color")[0] == "BR"
    for name in ("veg", "horizon"):
        assert _field(soils, name).decoded_as == "text"


def test_soils_text_columns_keep_their_content(soils: DbaseTable) -> None:
    first = soils.rows[0]
    assert first["sample"] == "8101"
    assert first["filesource"] == "Zacb_geochem_2005"
    assert first["date_"] == "15-Jun-05"
    assert first["comments"] == "zac ip station 1600"
    assert first["sampler"] == "AKA"


def test_soils_negative_and_sub_unit_assays_survive(soils: DbaseTable) -> None:
    """-1.0 (below detection) and 0.173 both sit inside the magnitude window."""
    assert _column(soils, "sb_ppm")[0] == -1.0
    assert _column(soils, "hg_ppm")[0] == 0.173
    assert _column(soils, "ag_ppm")[0] == 0.2


# ---------------------------------------------------------------------------
# MiscPoints_2005.dbf — ordinary ASCII dBASE, must not regress
# ---------------------------------------------------------------------------

def test_misc_points_shape(misc_points: DbaseTable) -> None:
    assert misc_points.record_count == 42
    assert misc_points.deleted_count == 0
    assert len(misc_points.rows) == 42
    assert [f.name for f in misc_points.fields] == ["OBJECTID", "Type", "Comments"]


def test_misc_points_ascii_numeric_stays_numeric(misc_points: DbaseTable) -> None:
    """OBJECTID is a genuine 'N' field of right-justified digits."""
    objectid = _field(misc_points, "OBJECTID")
    assert objectid.dbase_type == "N"
    assert objectid.decoded_as == "int32"
    values = _column(misc_points, "OBJECTID")
    assert values[:5] == [93, 94, 95, 96, 97]
    assert all(isinstance(v, int) for v in values)


def test_misc_points_text_columns(misc_points: DbaseTable) -> None:
    types = _column(misc_points, "Type")
    assert types[:5] == ["Misc", "Misc", "Misc", "Misc", "HandSample"]
    assert sorted(set(types)) == ["HandSample", "Misc", "Photo"]


def test_misc_points_interior_line_break_survives_padding_strip(misc_points: DbaseTable) -> None:
    """Trailing spaces go, the CRLF inside the sentence stays."""
    assert misc_points.rows[0]["Comments"] == "check if bm sampled along this\r\nzone."


def test_misc_points_ldid_0x57_does_not_change_the_result(misc_points: DbaseTable) -> None:
    """This file declares code page 0x57 where the MapInfo files declare 0x00.

    Neither may crash the reader, and neither drives the codec — the caller's
    `encoding` does.
    """
    assert MISC_POINTS.read_bytes()[29] == 0x57
    assert SITKA_TRENCH.read_bytes()[29] == 0x00
    assert read_dbase(MISC_POINTS, encoding="cp1252").rows[0]["Type"] == "Misc"


# ---------------------------------------------------------------------------
# alteration_riehle.dbf — ASCII dBASE with decimals
# ---------------------------------------------------------------------------

def test_alteration_shape_and_decimal_fields() -> None:
    table = read_dbase(ALTERATION)
    assert table.record_count == 10
    assert len(table.rows) == 10

    area = _field(table, "AREA")
    assert area.dbase_type == "N"
    assert area.decoded_as == "double"
    assert table.rows[0]["AREA"] == pytest.approx(29024.30078125)

    klass = _field(table, "CLASS")
    assert klass.decoded_as == "int32"
    assert table.rows[0]["CLASS"] == 500

    assert _column(table, "UNIT") == ["S"] * 10


# ---------------------------------------------------------------------------
# The GCP pair — MapInfo grading its own decode
# ---------------------------------------------------------------------------

#: Transcribed from tr006.4-geology_gcp.TAB, which MapInfo Discover wrote for
#: this exact table type. tr002.3-geology_gcp.DAT is the same table with its
#: .TAB missing, so its header declares all ten columns as 'C' and the reader
#: has to rediscover this list from the bytes alone.
GCP_DECLARED_TYPES = {
    "ID": "int32",
    "Use": "int32",           # 'Use Logical' — exposed as 0/1, see module docstring
    "Image_X": "int32",
    "Image_Y": "int32",
    "Map_X": "double",
    "Map_Y": "double",
    "RMS": "double",
    "ResidualX": "double",
    "ResidualY": "double",
    "Descriptio": "text",     # 'Description Char (100)', truncated to the 10-char DBF limit
}

GCP_DAT = REDSTAR / "Apollo Sitka" / "Trench" / "TR002" / "TR002.3" / "tr002.3-geology_gcp.DAT"
GCP_TAB = REDSTAR / "Apollo Sitka" / "Trench" / "TR006" / "tr006.4-geology_gcp.TAB"


def test_gcp_sidecar_still_declares_the_schema_this_test_was_written_against() -> None:
    """Guard the oracle itself — the test below is worthless if the .TAB moved."""
    declaration = GCP_TAB.read_text(encoding="latin-1")
    assert "Use Logical ;" in declaration
    assert "Map_X Float ;" in declaration
    assert "Image_X Integer ;" in declaration


def test_blind_decode_reproduces_the_types_mapinfo_declared() -> None:
    """Ten of ten, on a table the decode rule was never tuned against.

    The .DAT's own header calls every one of these columns 'C'. Recovering
    MapInfo's intended schema from the bytes — and agreeing with the sidecar
    it wrote for the sibling table — is the strongest available evidence that
    the magnitude window is measuring something real rather than fitting the
    two files the rule was derived from.
    """
    table = read_dbase(GCP_DAT)
    assert {f.name for f in table.fields} == set(GCP_DECLARED_TYPES)
    assert {f.dbase_type for f in table.fields} == {"C", "L"}   # the header's own claim

    recovered = {f.name: f.decoded_as for f in table.fields}
    assert recovered == GCP_DECLARED_TYPES


def test_gcp_values() -> None:
    table = read_dbase(GCP_DAT)
    assert len(table.rows) == 3
    assert _column(table, "ID") == [1, 2, 3]
    assert _column(table, "Image_X") == [1185, 1582, 2096]
    assert _column(table, "Descriptio") == ["Point 1", "Point 2", "Point 3"]
    # Map_X/Map_Y are UTM zone 4N metres and must land on the same trench as
    # the Sitka_trD midpoints, which were decoded from a different file.
    assert min(_column(table, "Map_X")) >= 400586
    assert max(_column(table, "Map_X")) <= 400864
    assert all(abs(v) < 10 for v in _column(table, "RMS"))


def test_logical_column_decodes_true_as_one() -> None:
    """MapInfo writes 0x01, not 'T'."""
    table = read_dbase(GCP_DAT)
    use = _field(table, "Use")
    assert use.dbase_type == "L"
    assert use.length == 1
    assert _column(table, "Use") == [1, 1, 1]

    raw = GCP_DAT.read_bytes()
    _count, header_len, record_len = struct.unpack("<IHH", raw[4:12])
    assert raw[header_len + 1 + 4] == 0x01      # deletion flag + ID(4), then Use


def _gcp_with_use_byte(tmp_path: Path, value: int) -> Path:
    """The real file with only the first record's Use byte changed."""
    raw = bytearray(GCP_DAT.read_bytes())
    _count, header_len, record_len = struct.unpack("<IHH", bytes(raw[4:12]))
    raw[header_len + 1 + 4] = value
    target = tmp_path / f"gcp_use_{value:02x}.DAT"
    target.write_bytes(bytes(raw))
    return target


def test_logical_false_is_zero_not_missing(tmp_path: Path) -> None:
    """0x00 means false here, and must not be swallowed as padding.

    This is the distinction the module's `_LOGICAL_FALSE` / `_LOGICAL_UNKNOWN`
    split exists for: a NUL is padding everywhere else in a dBASE record, but
    in a MapInfo logical cell it is a recorded answer.
    """
    table = read_dbase(_gcp_with_use_byte(tmp_path, 0x00))
    assert _field(table, "Use").decoded_as == "int32"
    assert _column(table, "Use") == [0, 1, 1]


def test_logical_unknown_is_none(tmp_path: Path) -> None:
    table = read_dbase(_gcp_with_use_byte(tmp_path, 0x20))
    assert _column(table, "Use") == [None, 1, 1]

    ascii_form = read_dbase(_gcp_with_use_byte(tmp_path, ord("F")))
    assert _column(ascii_form, "Use") == [0, 1, 1]


def test_undefined_logical_byte_demotes_the_column_to_text(tmp_path: Path) -> None:
    """An unrecognised flag costs the column its type, never its content."""
    table = read_dbase(_gcp_with_use_byte(tmp_path, ord("Z")))
    assert _field(table, "Use").decoded_as == "text"
    assert _column(table, "Use")[0] == "Z"


# ---------------------------------------------------------------------------
# Failure modes
# ---------------------------------------------------------------------------

def test_truncated_file_is_refused_by_name(tmp_path: Path) -> None:
    """Half a table that looks whole is the worst possible return value."""
    truncated = tmp_path / "Sitka_trD_cut.DAT"
    truncated.write_bytes(SITKA_TRENCH.read_bytes()[:-200])

    with pytest.raises(ValueError) as excinfo:
        read_dbase(truncated)

    message = str(excinfo.value)
    assert "Sitka_trD_cut.DAT" in message
    assert "truncated" in message
    assert "10 records" in message


def test_header_only_file_is_refused(tmp_path: Path) -> None:
    stub = tmp_path / "stub.dbf"
    stub.write_bytes(b"\x03\x73\x04\x11")

    with pytest.raises(ValueError, match="too short"):
        read_dbase(stub)


def test_missing_file_raises_file_not_found(tmp_path: Path) -> None:
    with pytest.raises(FileNotFoundError):
        read_dbase(tmp_path / "nope.dbf")


def test_decoded_as_predicts_the_python_type(sitka: DbaseTable, soils: DbaseTable) -> None:
    """The closed vocabulary is a contract: text->str, double->float, int32->int.

    A caller builds column types from `fields` without sampling `rows`, so a
    label that did not predict the value type would be worse than no label.
    """
    expected = {"text": str, "double": float, "int32": int}
    for table in (sitka, soils):
        for field in table.fields:
            for row in table.rows:
                value = row[field.name]
                if value is None:
                    continue
                assert isinstance(value, expected[field.decoded_as]), (
                    f"{field.name} is labelled {field.decoded_as} but holds {type(value).__name__}"
                )
