"""Surpac string file (.str) parser.

## Why this exists

``.str`` is the interchange format every mine-planning package can read, so it
is what arrives when someone exports level plans, pit outlines or slices
through a vein wireframe. It is also the format most likely to be read
*wrong*, because of one detail in the record layout:

    string_number, Y, X, Z, *descriptors

**Y comes before X.** That is the Surpac convention, it is not marked anywhere
in the file, and nothing about a mis-read file looks broken: the strings still
close, the levels still stack at 5 m, the polygons still render. They are just
mirrored about the 45-degree line, which puts the orebody somewhere it is not.
On the RedStar Shumagin sections the two columns are 6120684 and 399183 — a
UTM northing and a UTM easting, one an order of magnitude larger than the
other — so the mistake is detectable by eye, but only if you look, and only in
a projected CRS where the two ranges differ.

This module therefore does the swap ONCE, here, and hands the caller
``(x, y, z)`` in that order. ``SurpacString.points`` is east-first. Nothing
downstream should ever index a raw ``.str`` field again.

## What this module deliberately does NOT do

**It does not guess a CRS.** A ``.str`` carries no projection information of
any kind — no EPSG, no WKT, no sidecar convention. The numbers above are
"probably UTM zone 3N" only because of where Shumagin is, and that inference
belongs to the caller who knows the project, not to the reader that knows the
bytes. There is no EPSG code anywhere in this file, and adding one would turn
a reasonable guess into a recorded fact.

**It does not flatten Z.** These exports are level plans: every string sits at
one elevation and the SET of elevations is the dataset — 73 levels at exact
5 m spacing in the RedStar file. The geometry column those strings land in is
2D, so the elevation has to be carried as an attribute, and a parser that
dropped Z "because the geometry is 2D" would throw away the only thing that
distinguishes one section from another. ``level_z`` exists to make that
attribute trivial to carry.

**It does not close open strings.** 127 of the RedStar file's 129 strings
repeat their first vertex as their last; 2 do not, and their endpoints are
0.40 m and 0.73 m apart — a real gap in the digitising, not float noise.
Snapping those shut would invent 0.4 m of vein outline that nobody drew.
``closed`` reports what the file says and the caller decides.

## Format notes

Line 1 is a free-text title. Line 2 is the axis / coordinate-definition
record. Records follow until a terminator, and the file ends with an ``END``
sentinel:

    Z:\\...\\Main Plan Sections.str,,Generated by FracSIS 5.3,
    0,0.000,0.000,0.000,0.000,1.000,0.000
    1,6120684.44783417,399183.2878034668,125.0000249023437,
    ... more records for string 1 ...
    0,0.000,0.000,0.000
    ... string 2 ...
    0,0.000,0.000,0.000
    0,0.000,0.000,0.000,END

Note the trap in that listing: the axis record on line 2 and the string
terminators are both "string number 0" and are told apart by POSITION only.
A loop that starts at line 2 and applies the terminator rule uniformly emits a
phantom empty string before the real first one.

NOTE: Do NOT add `from __future__ import annotations` to this file.
It follows the convention of the parsers beside it, which are imported by
Dagster Config classes whose Pydantic introspection that import breaks.
"""

import logging
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

PARSER_NAME = "surpac_parser"
PARSER_VERSION = "1.0.0"

#: Extensions this parser claims. Surpac also writes ``.dtm`` (triangulated
#: surfaces) and ``.sss`` (string styles); neither is handled here.
SURPAC_EXTENSIONS = frozenset({".str"})

# Record layout. Named rather than inlined because ``parts[1]`` being the
# northing is the single most expensive assumption in this module.
_COL_STRING_NUMBER = 0
_COL_Y = 1              # northing
_COL_X = 2              # easting
_COL_Z = 3              # elevation
_FIRST_DESCRIPTOR_COL = 4

# Header lines, by position. See the format note above: position is the ONLY
# thing separating the axis record from a string terminator.
_TITLE_LINE = 0
_AXIS_LINE = 1

#: String number 0 marks the end of a string rather than a vertex of one.
_TERMINATOR_STRING_NUMBER = 0

#: Descriptor written on the final terminator of a complete file.
_END_SENTINEL = "END"

#: A string counts as FLAT when every vertex agrees on Z to within this many
#: metres. It cannot be zero: FracSIS writes each vertex's elevation through
#: its own float round-trip, so a nominal 125 m level arrives as a mix of
#: 125.0000249023437 and 125.0000096435547 and 64 of the RedStar file's 129
#: strings carry more than one *bit-distinct* Z. The largest spread measured
#: within a single string is 4.6e-5 m — 46 microns. One millimetre sits three
#: orders of magnitude above that noise and three-and-a-half below the 5 m
#: level spacing, so it can neither split one level in two nor merge two.
FLAT_TOLERANCE_M = 1e-3

#: ``level_z`` is rounded to millimetres for the same reason. Reporting the
#: raw mean would hand the caller 129 near-duplicate elevations to key a
#: section index on instead of the 73 distinct levels the surveyor drew.
_LEVEL_DECIMALS = 3


# ---------------------------------------------------------------------------
# Result dataclasses
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class SurpacString:
    """One terminator-delimited run of vertices.

    A ``.str`` may use the same string number for several disjoint runs — a
    level plan with two separate lenses on it is normal. Each run becomes its
    own ``SurpacString``, so ``string_number`` is NOT unique across a file.
    Concatenating same-numbered runs would draw a segment joining two lenses
    that are not connected.
    """

    #: The number in column 1. Groups strings by level, seam or classification
    #: in whatever scheme the author used; it carries no meaning to us.
    string_number: int

    #: Vertices as ``(x, y, z)`` — EASTING, NORTHING, elevation. Already
    #: swapped out of the file's Y,X,Z column order; see the module docstring.
    points: list[tuple[float, float, float]]

    #: The file repeats the first vertex verbatim as the last.
    #:
    #: This is a statement about the vertex list and nothing more. A two-point
    #: string ``A,A`` satisfies it and encloses no area, so a caller building
    #: polygons must still reject rings with fewer than three distinct
    #: vertices — ``closed`` will not do that for it.
    closed: bool

    #: The single elevation this string sits at, to the millimetre, or None
    #: when its vertices span more than ``FLAT_TOLERANCE_M``. None means the
    #: string is a genuine 3D polyline (a drillhole trace, a wireframe edge),
    #: not that the elevation is missing.
    level_z: float | None


@dataclass(frozen=True)
class SurpacFile:
    """Everything a ``.str`` says, with nothing inferred on top of it."""

    #: Line 1 verbatim, minus the padding commas the writer left on the end.
    #: Not split into fields: it is free text living in a comma-delimited
    #: file, and Windows paths are allowed to contain commas.
    title: str

    strings: list[SurpacString]

    #: ``(minx, miny, maxx, maxy)`` over every vertex, in the file's own
    #: units. Provided because the caller's next question is always "what CRS
    #: is this in", and the magnitude of the two ranges is the only evidence
    #: the file offers. Answering that question is the caller's job.
    bounds: tuple[float, float, float, float]


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------

def _read_text(path: Path) -> str:
    """Decode a ``.str``, preferring UTF-8 and falling back to cp1252.

    Surpac and FracSIS are Windows tools, so the only bytes that are ever
    non-ASCII live in the title line's path or in a descriptor — an accented
    surname in a folder name is the usual case. Decoding is lossy rather than
    strict on the fallback because one unmappable byte in a title must not
    cost the caller 9,727 coordinates.
    """
    raw = path.read_bytes()
    try:
        return raw.decode("utf-8")
    except UnicodeDecodeError:
        logger.info("Surpac parser: '%s' is not UTF-8 — decoding as cp1252", path)
        return raw.decode("cp1252", errors="replace")


def _clean_title(line: str) -> str:
    """Strip the trailing empty fields a writer pads the title line with.

    FracSIS emits ``<path>,,Generated by FracSIS 5.3,`` — the interior comma
    pair is part of the text and stays, the one on the end is padding.
    """
    return line.strip().rstrip(",").strip()


def _parse_string_number(line: str) -> int | None:
    """The record's string number, or None when the first field is not one.

    The exception is the answer, not a failure: a Surpac file's title line and
    its trailing ``END`` record both have a non-numeric first field, and the
    caller uses None to tell a record apart from a header. Logged anyway,
    because a file whose DATA rows land here is malformed in a way the caller
    counts but cannot explain, and the offending text is the explanation.
    """
    field = line.split(",", 1)[0].strip()
    try:
        return int(field)
    except ValueError:
        logger.debug("Surpac: non-numeric string number %r — treated as a header", field)
        return None


def _descriptor_text(parts: list[str]) -> str:
    """The non-empty descriptor fields after Z, joined; ``""`` when there are none.

    Descriptors are optional and the writer pads with empty ones, so every
    data row in the RedStar file has a fifth field and none of them says
    anything. Testing ``len(parts) > 4`` would report all 9,727 of them.
    """
    return ",".join(p.strip() for p in parts[_FIRST_DESCRIPTOR_COL:] if p.strip())


def _warn_malformed(path: Path, lineno: int, line: str, reason: str) -> None:
    """Report a skipped record. Truncated: a bad line can be arbitrarily long."""
    logger.warning(
        "Surpac parser: '%s' line %d skipped — %s: %r", path, lineno, reason, line[:80],
    )


def _level_of(points: list[tuple[float, float, float]]) -> float | None:
    """The one elevation *points* share, or None if they do not share one.

    The mean is used rather than the first vertex's Z so that the reported
    level does not depend on which end of the string was digitised first.
    """
    if not points:
        return None

    zs = [z for _, _, z in points]
    if max(zs) - min(zs) > FLAT_TOLERANCE_M:
        return None

    return round(sum(zs) / len(zs), _LEVEL_DECIMALS)


def _build_string(
    string_number: int,
    points: list[tuple[float, float, float]],
) -> SurpacString:
    """Finish one accumulated run into an immutable record."""
    return SurpacString(
        string_number=string_number,
        points=points,
        closed=len(points) >= 2 and points[0] == points[-1],
        level_z=_level_of(points),
    )


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------

def read_surpac_strings(path: str | Path) -> SurpacFile:
    """Read a Surpac string file into strings of ``(x, y, z)`` vertices.

    The file stores ``string_number, Y, X, Z`` — northing before easting. The
    returned ``points`` are ``(x, y, z)``, east first. See the module
    docstring for why that swap is the whole point of this function.

    Args:
        path: Path to the ``.str`` file on the local filesystem.

    Returns:
        SurpacFile. ``bounds`` spans every vertex of every string, in the
        file's own (unknown) units and CRS.

    Raises:
        FileNotFoundError: if *path* does not exist.
        ValueError: if the file has no title line, or carries no vertices at
            all. A vertex-free ``.str`` is refused rather than returned with a
            fabricated ``bounds``: there is no honest bounding box for an
            empty set, and a caller reading ``(0, 0, 0, 0)`` as a real extent
            would place the file at the origin of whatever CRS it picked.
    """
    path = Path(path)
    logger.info("Surpac parser: opening '%s'", path)

    lines = _read_text(path).splitlines()
    if not lines:
        raise ValueError(f"Surpac file '{path}' is empty — no title line.")

    title = _clean_title(lines[_TITLE_LINE])

    # The axis record is identified by position, never by content: it opens
    # with string number 0, exactly as every string terminator does. Skipping
    # it blindly would be wrong the other way round, so a line 2 that carries
    # a real string number is treated as data and the missing axis reported.
    first_record = _AXIS_LINE
    if len(lines) > _AXIS_LINE:
        axis_number = _parse_string_number(lines[_AXIS_LINE])
        if axis_number == _TERMINATOR_STRING_NUMBER:
            first_record = _AXIS_LINE + 1
        else:
            logger.warning(
                "Surpac parser: '%s' line 2 is not an axis record (%r) — "
                "reading it as data; the file may be missing its header.",
                path,
                lines[_AXIS_LINE][:80],
            )

    strings: list[SurpacString] = []
    pending_number: int | None = None
    pending_points: list[tuple[float, float, float]] = []
    malformed_rows = 0
    descriptor_rows = 0
    last_terminator_descriptor: str | None = None

    for lineno, line in enumerate(lines[first_record:], start=first_record + 1):
        if not line.strip():
            continue

        parts = line.split(",")
        number = _parse_string_number(line)

        if number is None:
            malformed_rows += 1
            _warn_malformed(path, lineno, line, "string number is not an integer")
            continue

        if number == _TERMINATOR_STRING_NUMBER:
            # Terminators arrive back-to-back at the end of a file (the last
            # string's, then the END sentinel's), so an empty run here is
            # normal and must not become a zero-vertex string.
            if pending_number is not None and pending_points:
                strings.append(_build_string(pending_number, pending_points))
            pending_number, pending_points = None, []
            last_terminator_descriptor = _descriptor_text(parts)
            continue

        try:
            y = float(parts[_COL_Y])
            x = float(parts[_COL_X])
            z = float(parts[_COL_Z])
        except (IndexError, ValueError):
            malformed_rows += 1
            _warn_malformed(path, lineno, line, "coordinate fields missing or non-numeric")
            continue

        if _descriptor_text(parts):
            descriptor_rows += 1

        # A string number that changes without an intervening terminator is
        # malformed, but the vertices on either side are not: close the run
        # that was open rather than appending the new string's points to it.
        if pending_number is not None and number != pending_number:
            logger.warning(
                "Surpac parser: '%s' line %d starts string %d while string %d is still "
                "open — closing %d at the boundary.",
                path, lineno, number, pending_number, pending_number,
            )
            if pending_points:
                strings.append(_build_string(pending_number, pending_points))
            pending_points = []

        pending_number = number
        pending_points.append((x, y, z))   # THE SWAP: file is Y,X — we emit X,Y.

    # An unterminated final string still has its vertices; keep them.
    if pending_number is not None and pending_points:
        logger.warning(
            "Surpac parser: '%s' ends inside string %d — no terminator record.",
            path, pending_number,
        )
        strings.append(_build_string(pending_number, pending_points))

    if last_terminator_descriptor != _END_SENTINEL:
        logger.warning(
            "Surpac parser: '%s' does not end with the '%s' record — it may be truncated.",
            path, _END_SENTINEL,
        )

    total_points = sum(len(s.points) for s in strings)
    if total_points == 0:
        raise ValueError(f"Surpac file '{path}' contains no vertex records.")

    xs = [x for s in strings for x, _, _ in s.points]
    ys = [y for s in strings for _, y, _ in s.points]
    bounds = (min(xs), min(ys), max(xs), max(ys))

    flat = sum(1 for s in strings if s.level_z is not None)
    logger.info(
        "Surpac parser: '%s' — %d strings, %d vertices, %d flat, %d closed; "
        "X %.3f–%.3f, Y %.3f–%.3f (CRS unknown, caller decides)",
        path, len(strings), total_points, flat,
        sum(1 for s in strings if s.closed),
        bounds[0], bounds[2], bounds[1], bounds[3],
    )

    if malformed_rows:
        logger.warning(
            "Surpac parser: '%s' — %d row(s) skipped as malformed.", path, malformed_rows,
        )
    if descriptor_rows:
        # Descriptors are not part of SurpacFile. Saying so out loud beats
        # dropping attribute data with no trace of having seen it.
        logger.warning(
            "Surpac parser: '%s' — %d row(s) carry descriptor fields, which this "
            "parser does not return.", path, descriptor_rows,
        )

    return SurpacFile(title=title, strings=strings, bounds=bounds)
