#!/usr/bin/env bash
# Emit a repo-free CloudShell script that runs the rerank-threshold probe
# inside the VPC: the sibling of make_probe_bundle.sh (Cohere wire probe).
#
#   bash ops/rehearsal/make_rerank_threshold_bundle.sh > /tmp/rerank.sh
#   # upload /tmp/rerank.sh to CloudShell, then:
#   bash rerank.sh                          # corpus contrast, defaults
#   bash rerank.sh --harvest-since 2026-09-08   # plus the answer_runs harvest
#
# The bundle re-implements nothing. It carries the committed
# run_rerank_threshold_probe.sh, rerank_threshold_probe.py and
# _probe_verdict.py as one gzip+base64 tarball, unpacks them into a temp dir
# laid out like the repo, and runs the runner, exactly as
# scripts/tests/run_rerank_threshold_probe_test.sh exercises it. Arguments are
# passed through to the probe.
#
# The report is written to ~/rerank-threshold-reports/ (only if it measured
# something: the runner's own rule) and printed in full at the end, so it can
# be downloaded and committed to ops/validation/reports/.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"

PAYLOAD=$(tar -C "$REPO_ROOT" --owner=0 --group=0 --numeric-owner --mtime='2026-01-01' -cf - \
            ops/rehearsal/run_rerank_threshold_probe.sh \
            ops/validation/rerank_threshold_probe.py \
            ops/validation/_probe_verdict.py \
          | gzip -n -9 | base64 -w 76)

cat <<BUNDLE
#!/usr/bin/env bash
# GENERATED by ops/rehearsal/make_rerank_threshold_bundle.sh. Do not edit here.
# Measures RERANKER_SCORE_THRESHOLD_HOSTED evidence as a one-off task inside
# the VPC, through the deployed reranker adapter and task role. Needs no repo
# checkout. Changes nothing: it writes a report for a human to read.
# Report: ~/rerank-threshold-reports/ (written only if it measured something).
set -euo pipefail
for tool in aws jq tar gzip base64; do
  command -v "\$tool" >/dev/null 2>&1 || { echo "missing required tool: \$tool" >&2; exit 1; }
done

D=\$(mktemp -d)
trap 'rm -rf "\$D"' EXIT
read -r -d '' PAYLOAD <<'PAYLOADEOF' || true
${PAYLOAD}
PAYLOADEOF
printf '%s' "\$PAYLOAD" | base64 -d | tar -C "\$D" -xzf -

export PROBE_REPORTS_DIR="\${PROBE_REPORTS_DIR:-\$HOME/rerank-threshold-reports}"
bash "\$D/ops/rehearsal/run_rerank_threshold_probe.sh" "\$@"

REPORT=\$(ls -t "\$PROBE_REPORTS_DIR"/rerank_threshold_*.json | head -1)
echo
echo "=== report: \$REPORT ======================================="
cat "\$REPORT"
echo
echo "=== end of report =========================================="
echo "Send this file back (CloudShell: Actions -> Download file -> \$REPORT)"
echo "so it can be committed to ops/validation/reports/."
BUNDLE
