#!/usr/bin/env bash
# Emit a repo-free CloudShell script that runs the Cohere wire-contract probe
# inside the VPC — the sibling of make_cloudshell_bundle.sh (step 5) and
# make_step6_bundle.sh (step 6).
#
#   bash ops/rehearsal/make_probe_bundle.sh > /tmp/probe.sh
#   # upload /tmp/probe.sh to CloudShell, then: bash probe.sh
#
# The bundle does not re-implement anything. It carries the committed
# run_cohere_probe.sh, cohere_probe.py, _probe_verdict.py and the fixture PDF
# as one gzip+base64 tarball, unpacks them into a temp dir laid out like the
# repo, and runs the runner exactly as CI's scripts/tests/run_cohere_probe_test.sh
# exercises it. A second copy of the logic would be the drift this PR has
# already fixed twice.
#
# The report is written to ~/cohere-probe-reports/ (only if it verified
# something — the runner's own rule) and printed in full at the end, so it
# can be copied or downloaded and committed to ops/validation/reports/.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
PDF_REL="src/fastapi/tests/fixtures/ocr/PLS-2024-Technical-Report.pdf"

PAYLOAD=$(tar -C "$REPO_ROOT" --owner=0 --group=0 --numeric-owner --mtime='2026-01-01' -cf - \
            ops/rehearsal/run_cohere_probe.sh \
            ops/validation/cohere_probe.py \
            ops/validation/_probe_verdict.py \
            "$PDF_REL" \
          | gzip -n -9 | base64 -w 76)

cat <<BUNDLE
#!/usr/bin/env bash
# GENERATED by ops/rehearsal/make_probe_bundle.sh — do not edit here.
# Runs the Cohere wire-contract probe as a one-off task inside the VPC, using
# the deployed service's own COHERE_API_KEY and egress. Needs no repo checkout.
# Report: ~/cohere-probe-reports/ (written only if it verified something).
set -euo pipefail
for tool in aws jq tar gzip base64; do
  command -v "\$tool" >/dev/null 2>&1 || { echo "missing required tool: \$tool" >&2; exit 1; }
done

D=\$(mktemp -d)
trap 'rm -rf "\$D"' EXIT
read -r -d '' PAYLOAD <<'PAYLOADEOF' || true
${PAYLOAD}
PAYLOADEOF
printf '%s' "\$PAYLOAD" | base64 -d | tar -C "\$D" -xzf -

export PROBE_REPORTS_DIR="\${PROBE_REPORTS_DIR:-\$HOME/cohere-probe-reports}"
bash "\$D/ops/rehearsal/run_cohere_probe.sh"

REPORT=\$(ls -t "\$PROBE_REPORTS_DIR"/cohere_probe_*.json | head -1)
echo
echo "=== report: \$REPORT ======================================="
cat "\$REPORT"
echo
echo "=== end of report =========================================="
echo "Send this file back (CloudShell: Actions -> Download file -> \$REPORT)"
echo "so it can be committed to ops/validation/reports/ for aws-preflight A-11."
BUNDLE
