#!/usr/bin/env bash
# Emit a repo-free seed+ingest script for CloudShell, built FROM the
# committed sources.
#
# Why this is a generator rather than a checked-in standalone script:
# CloudShell's home directory does not survive a session recycle, which
# happened three times during the 2026-09-18 rehearsal, each time taking the
# repo checkout with it. The obvious fix — commit a self-contained script
# with the SQL pasted into it — creates a second copy of
# seed_multitenant_corpus.sql that drifts the first time anyone edits one and
# not the other. Generating it means the bundle cannot disagree with the
# source it came from.
#
#   bash ops/rehearsal/make_cloudshell_bundle.sh > /tmp/bundle.sh
#   # upload /tmp/bundle.sh to CloudShell, then: bash bundle.sh
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# The executable core of the seed, without its comment header or the psql
# \echo reporting (which needs a psql frontend the container may not run
# interactively). The verification SELECT is re-added below.
SEED_CORE=$(sed -n '/^BEGIN;/,/^COMMIT;/p' "${HERE}/seed_multitenant_corpus.sql")

cat <<BUNDLE
#!/usr/bin/env bash
# GENERATED by ops/rehearsal/make_cloudshell_bundle.sh — do not edit here.
# Seeds the two-tenant corpus, then ingests one PDF. Needs no repo checkout.
set -euo pipefail
CLUSTER=georag
PID=aaaaaaaa-1111-4111-8111-aaaaaaaaaaaa
WID=11111111-aaaa-4aaa-8aaa-111111111111

NET=\$(aws ecs describe-services --cluster \$CLUSTER --services fastapi \\
        --query 'services[0].networkConfiguration.awsvpcConfiguration')
SUBNETS=\$(echo "\$NET" | jq -r '.subnets|join(",")')
SG=\$(echo "\$NET" | jq -r '.securityGroups|join(",")')
NETCFG="awsvpcConfiguration={subnets=[\$SUBNETS],securityGroups=[\$SG],assignPublicIp=DISABLED}"

wait_and_log() {
  aws ecs wait tasks-stopped --cluster \$CLUSTER --tasks "\$1"
  aws logs get-log-events --log-group-name /ecs/georag \\
    --log-stream-name "\$2/\$2/\${1##*/}" \\
    --query 'events[].message' --output text 2>/dev/null | tr '\\t' '\\n' || echo "(no log)"
  aws ecs describe-tasks --cluster \$CLUSTER --tasks "\$1" \\
    --query 'tasks[0].containers[0].exitCode' --output text
}

echo "=== 1/2  seed the two-tenant corpus ============================="
read -r -d '' SEED_SQL <<'SQLEOF' || true
${SEED_CORE}
SELECT w.slug AS workspace, p.slug AS project, c.hole_id, c.easting
FROM silver.collars c
JOIN silver.projects p   ON p.project_id   = c.project_id
JOIN silver.workspaces w ON w.workspace_id = p.workspace_id
WHERE w.slug IN ('rehearsal-meridian','rehearsal-cascade') ORDER BY c.easting;
SQLEOF

SEED_ARN=\$(aws ecs run-task --cluster \$CLUSTER --task-definition georag-migrate \\
  --launch-type FARGATE --network-configuration "\$NETCFG" \\
  --overrides "\$(jq -n --arg sql "\$SEED_SQL" '{containerOverrides:[{
      name:"migrate",
      command:["sh","-lc","printf %s \\"\\\$GEORAG_SQL\\" | psql \\"\\\$DATABASE_URL\\" -v ON_ERROR_STOP=1"],
      environment:[{name:"GEORAG_SQL",value:\$sql}]}]}')" \\
  --query 'tasks[0].taskArn' --output text)
echo "seed task: \$SEED_ARN"
SEED_CODE=\$(wait_and_log "\$SEED_ARN" migrate)
echo "seed exit: \$SEED_CODE"
# Stop here on failure: firing the trigger at a project that does not exist
# returns a 403 from require_active_project, which reads like a permissions
# problem rather than a missing row.
[ "\$SEED_CODE" = "0" ] || { echo "SEED FAILED — not running ingest"; exit 1; }

echo
echo "=== 2/2  upload the fixture PDF and trigger ingest_pdf =========="
read -r -d '' PY <<PYEOF || true
import json, os, urllib.request, uuid, boto3
pid, wid = "\$PID", "\$WID"
src = "/app/tests/fixtures/ocr/PLS-2024-Technical-Report.pdf"
key = f"reports/{pid}/rehearsal-{uuid.uuid4()}.pdf"
bucket = os.environ["AWS_BUCKET_BRONZE"]
boto3.client("s3").upload_file(src, bucket, key)
size = os.path.getsize(src)
print(f"uploaded s3://{bucket}/{key} ({size} bytes)")
body = json.dumps({"workspace_id": wid, "project_id": pid, "minio_key": key,
                   "file_size": size, "correlation_token": str(uuid.uuid4())}).encode()
req = urllib.request.Request(
    os.environ["FASTAPI_INTERNAL_URL"].rstrip("/") + "/internal/v1/shadow/ingest_pdf/trigger",
    data=body, headers={"Content-Type": "application/json",
                        "X-Service-Key": os.environ["FASTAPI_SERVICE_KEY"]})
with urllib.request.urlopen(req, timeout=60) as r:
    print("trigger:", r.status, r.read().decode()[:400])
PYEOF

ING_ARN=\$(aws ecs run-task --cluster \$CLUSTER --task-definition georag-fastapi \\
  --launch-type FARGATE --network-configuration "\$NETCFG" \\
  --overrides "\$(jq -n --arg py "\$PY" '{containerOverrides:[{
      name:"fastapi", command:["python3","-c",\$py]}]}')" \\
  --query 'tasks[0].taskArn' --output text)
echo "ingest task: \$ING_ARN"
echo "ingest exit: \$(wait_and_log "\$ING_ARN" fastapi)"
echo
echo "Ingestion DISPATCHED. 202 means Hatchet ACCEPTED the run, not that it"
echo "finished — it now parses / chunks / embeds / indexes for some minutes."
BUNDLE
