#!/usr/bin/env bash
# Emit a repo-free seed+verify script for CloudShell — rehearsal step 6 —
# built FROM the committed SQL.
#
# Why a generator and not a committed standalone script: CloudShell's home
# directory does not survive a session recycle, which happened three times
# during the 2026-09-18 rehearsal, each time taking the checkout with it. A
# repo-free bundle is a real operational need. But pasting the SQL into a
# second committed file creates a copy that drifts the first time someone
# edits one and not the other — the shape this PR has already fixed twice
# (the probe verdict module, the redis manifest guard). Generating means the
# bundle cannot disagree with its source.
#
#   bash ops/rehearsal/make_step6_bundle.sh > /tmp/step6.sh
#   # upload /tmp/step6.sh to CloudShell, then: bash step6.sh
#
# The bundle carries the SQL gzip+base64 for the same reason the runner does:
# ECS RunTask caps the overrides structure at 8192 characters and the verify
# SQL alone serialises past that uncompressed.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SEED_B64=$(gzip -n -9 -c "${HERE}/seed_multitenant_corpus.sql" | base64 -w0)
VERIFY_B64=$(gzip -n -9 -c "${HERE}/verify_tenant_fence.sql" | base64 -w0)

emit_driver () {   # $1 = base64 SQL, $2 = expected acks, $3 = label
  cat <<PYEOF
import asyncio, base64, re, sys, zlib
import asyncpg
from app.db.dsn import build_dsn

SQL = zlib.decompress(base64.b64decode("$1"), 31).decode()
EXPECT = $2
LABEL = "$3"

seen = []

def _log(_conn, msg):
    text = getattr(msg, "message", str(msg))
    seen.append(text)
    print(text, flush=True)

async def main():
    conn = await asyncpg.connect(build_dsn(scheme="postgresql", include_sslmode=True))
    conn.add_log_listener(_log)
    try:
        await conn.execute(SQL)
    finally:
        await conn.close()

asyncio.run(main())

acks = sorted({m.group(0) for line in seen
               for m in [re.search(r"\[(?:CHECK-OK \d|SEED-OK|TEARDOWN-OK)\]", line)] if m})
print("acknowledgements: %d/%d %s" % (len(acks), EXPECT, acks), flush=True)
if len(acks) != EXPECT:
    print("::error::%s: %d of %d checks acknowledged - the script did not fully "
          "execute, so this is NOT a pass" % (LABEL, len(acks), EXPECT), flush=True)
    sys.exit(1)
print("%s OK" % LABEL, flush=True)
PYEOF
}

SEED_PY=$(emit_driver "$SEED_B64" 1 seed_multitenant_corpus.sql)
VERIFY_PY=$(emit_driver "$VERIFY_B64" 5 verify_tenant_fence.sql)

cat <<BUNDLE
#!/usr/bin/env bash
# GENERATED by ops/rehearsal/make_step6_bundle.sh — do not edit here.
# Rehearsal step 6: seed the two-tenant corpus into the LIVE database, then
# verify the Martin tenant fence against it. Needs no repo checkout.
#
# Runs on the georag-fastapi task definition: it is the only image in this
# deployment with a Postgres driver. The laravel/migrate image has libpq-dev
# for PHP's pdo_pgsql but no psql binary, no DATABASE_URL, and an entryPoint
# that silently mangles a command override into a no-op that exits 0.
set -euo pipefail
CLUSTER=georag

NET=\$(aws ecs describe-services --cluster \$CLUSTER --services fastapi \\
        --query 'services[0].networkConfiguration.awsvpcConfiguration')
SUBNETS=\$(echo "\$NET" | jq -r '.subnets|join(",")')
SG=\$(echo "\$NET" | jq -r '.securityGroups|join(",")')
NETCFG="awsvpcConfiguration={subnets=[\$SUBNETS],securityGroups=[\$SG],assignPublicIp=DISABLED}"

run_sql () {   # \$1 = label, \$2 = python driver
  local arn code
  arn=\$(aws ecs run-task --cluster \$CLUSTER --task-definition georag-fastapi \\
    --launch-type FARGATE --network-configuration "\$NETCFG" \\
    --overrides "\$(jq -n --arg py "\$2" '{containerOverrides:[{name:"fastapi",command:["python3","-c",\$py]}]}')" \\
    --query 'tasks[0].taskArn' --output text)
  echo "\$1 task: \$arn"
  aws ecs wait tasks-stopped --cluster \$CLUSTER --tasks "\$arn"
  echo "-- output ------------------------------------------------"
  aws logs get-log-events --log-group-name /ecs/georag \\
    --log-stream-name "fastapi/fastapi/\${arn##*/}" \\
    --query 'events[].message' --output text 2>/dev/null | tr '\\t' '\\n' || echo "(no log)"
  echo "----------------------------------------------------------"
  code=\$(aws ecs describe-tasks --cluster \$CLUSTER --tasks "\$arn" \\
           --query 'tasks[0].containers[0].exitCode' --output text)
  echo "\$1 exit: \$code"
  [ "\$code" = "0" ] || return 1
}

read -r -d '' SEED_PY <<'SEEDEOF' || true
${SEED_PY}
SEEDEOF

read -r -d '' VERIFY_PY <<'VERIFYEOF' || true
${VERIFY_PY}
VERIFYEOF

echo "=== 1/2  seed the two-tenant corpus ============================="
# Stop before verifying if the seed failed: verify_tenant_fence.sql would then
# fail at its co-location precondition and blame the coordinates for what was
# really a corpus that never landed.
run_sql seed "\$SEED_PY" || { echo "SEED FAILED — not verifying"; exit 1; }

echo
echo "=== 2/2  verify the Martin tenant fence ========================="
run_sql verify "\$VERIFY_PY" || { echo "STEP 6 FAILED"; exit 1; }
echo
echo "STEP 6 OK — the tenant fence holds on the live database."
BUNDLE
