#!/usr/bin/env bash
# Emit a repo-free script for rehearsal step 5 — seed, ingest, status, query —
# built FROM the committed sources.
#
# Why a generator and not a committed standalone script: CloudShell's home
# directory does not survive a session recycle, which happened three times
# during the 2026-09-18 rehearsal, each time taking the checkout with it. A
# repo-free bundle is a real operational need. But pasting the SQL into a
# second committed file creates a copy that drifts the first time someone edits
# one and not the other — the shape this PR has already fixed twice (the probe
# verdict module, the redis manifest guard). Generating means the bundle cannot
# disagree with its source.
#
#   bash ops/rehearsal/make_cloudshell_bundle.sh > /tmp/step5.sh
#   # upload /tmp/step5.sh to CloudShell, then:
#   bash step5.sh ingest    # seed the corpus + upload and dispatch the PDF
#   bash step5.sh status    # poll until the passages are embedded
#   bash step5.sh query     # the actual step-5 assertion
#
# ALL FOUR PHASES, not just seed+ingest. The first version of this generator
# emitted seed+ingest only, leaving `status` and `query` to
# ops/rehearsal/run_step5.sh — which needs the checkout this bundle exists
# because you do not have. Step 5 was therefore un-runnable end to end in the
# one environment the bundle was built for.
#
# The seed travels gzip+base64 through the same asyncpg driver step 6 uses,
# rather than the sed-extracted BEGIN..COMMIT the first version carried. That
# extraction dropped everything after COMMIT — which is now the [SEED-OK]
# assertion — so a half-landed corpus would have gone unnoticed here while
# failing loudly through run_against_deployment.sh. One mechanism, one
# behaviour.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PID="${PROJECT_ID:-aaaaaaaa-1111-4111-8111-aaaaaaaaaaaa}"
WID="${WORKSPACE_ID:-11111111-aaaa-4aaa-8aaa-111111111111}"
SEED_B64=$(gzip -n -9 -c "${HERE}/seed_multitenant_corpus.sql" | base64 -w0)

cat <<BUNDLE
#!/usr/bin/env bash
# GENERATED by ops/rehearsal/make_cloudshell_bundle.sh — do not edit here.
# Rehearsal step 5: prove one real query streams, cites a REAL source_chunk_id
# and terminates cleanly. Needs no repo checkout.
#
#   bash step5.sh ingest    seed the two-tenant corpus, then dispatch ingest_pdf
#   bash step5.sh status    poll until the passages carry embedding_id
#   bash step5.sh query     the step-5 assertion
#
# ingest and query are separate commands because they have different shapes.
# ingest kicks off a Hatchet workflow and returns immediately; the
# parse/chunk/embed/index chain then runs for minutes. Running them as one
# command means guessing a sleep, and a guessed sleep produces a red run that
# only means "not finished yet".
set -euo pipefail
CLUSTER=georag
ACTION="\${1:-query}"
PID=${PID}
WID=${WID}
QUESTION="\${REHEARSAL_QUESTION:-What does this project contain?}"

command -v jq >/dev/null || { echo "jq is required" >&2; exit 2; }

NET=\$(aws ecs describe-services --cluster \$CLUSTER --services fastapi \\
        --query 'services[0].networkConfiguration.awsvpcConfiguration')
SUBNETS=\$(echo "\$NET" | jq -r '.subnets|join(",")')
SG=\$(echo "\$NET" | jq -r '.securityGroups|join(",")')
if [ -z "\$SUBNETS" ] || [ "\$SUBNETS" = "null" ]; then
  echo "could not read the fastapi service's subnets from cluster \$CLUSTER" >&2
  exit 1
fi
NETCFG="awsvpcConfiguration={subnets=[\$SUBNETS],securityGroups=[\$SG],assignPublicIp=DISABLED}"

run_task () {   # \$1 = label, \$2 = overrides JSON; echoes the exit code
  local arn code
  arn=\$(aws ecs run-task --cluster \$CLUSTER --task-definition georag-fastapi \\
    --launch-type FARGATE --network-configuration "\$NETCFG" \\
    --overrides "\$2" --query 'tasks[0].taskArn' --output text)
  echo "\$1 task: \$arn" >&2
  aws ecs wait tasks-stopped --cluster \$CLUSTER --tasks "\$arn" >&2
  echo "-- \$1 output --------------------------------------------" >&2
  aws logs get-log-events --log-group-name /ecs/georag \\
    --log-stream-name "fastapi/fastapi/\${arn##*/}" \\
    --query 'events[].message' --output text 2>/dev/null | tr '\\t' '\\n' >&2 \\
    || echo "(could not read the task log)" >&2
  echo "----------------------------------------------------------" >&2
  code=\$(aws ecs describe-tasks --cluster \$CLUSTER --tasks "\$arn" \\
           --query 'tasks[0].containers[0].exitCode' --output text)
  echo "\$code"
}

# ── the seed, through the same asyncpg driver step 6 uses ──────────────────
read -r -d '' SEED_PY <<'SEEDEOF' || true
import asyncio, base64, re, sys, zlib
import asyncpg
from app.db.dsn import build_dsn

SQL = zlib.decompress(base64.b64decode("${SEED_B64}"), 31).decode()

seen = []

def _log(_conn, msg):
    text = getattr(msg, "message", str(msg))
    seen.append(text)
    print(text, flush=True)

async def main():
    conn = await asyncpg.connect(build_dsn(scheme="postgresql", include_sslmode=True))
    conn.add_log_listener(_log)
    try:
        await conn.execute(SQL)
    finally:
        await conn.close()

asyncio.run(main())

acks = sorted({m.group(0) for line in seen
               for m in [re.search(r"\[SEED-OK\]", line)] if m})
print("acknowledgements: %d/1 %s" % (len(acks), acks), flush=True)
if len(acks) != 1:
    print("::error::seed_multitenant_corpus.sql: 0 of 1 checks acknowledged - "
          "the script did not fully execute, so this is NOT a pass", flush=True)
    sys.exit(1)
print("seed_multitenant_corpus.sql OK", flush=True)
SEEDEOF

# ── the ingest TRIGGER only. The PDF is uploaded from CloudShell, not from
#    inside the task.
#
#    The first version did boto3.upload_file("/app/tests/fixtures/ocr/..."),
#    on the stated grounds that the fixture "ships in the image". It does not:
#    docker/fastapi.Dockerfile.dockerignore excludes **/tests/fixtures, so
#    the file is not even in the build context. The live run failed with
#    FileNotFoundError. Uploading from the shell needs no image change and no
#    ~25-minute CD cycle. ────────────────────────────────────────────────────
read -r -d '' INGEST_PY <<'INGESTEOF' || true
import json, os, urllib.request, uuid

pid, wid = "${PID}", "${WID}"
key  = os.environ["REHEARSAL_S3_KEY"]
size = int(os.environ["REHEARSAL_FILE_SIZE"])
print(f"triggering ingest_pdf for s3 key {key} ({size} bytes)", flush=True)

body = json.dumps({"workspace_id": wid, "project_id": pid, "minio_key": key,
                   "file_size": size, "correlation_token": str(uuid.uuid4())}).encode()
req = urllib.request.Request(
    os.environ["FASTAPI_INTERNAL_URL"].rstrip("/") + "/internal/v1/shadow/ingest_pdf/trigger",
    data=body, headers={"Content-Type": "application/json",
                        "X-Service-Key": os.environ["FASTAPI_SERVICE_KEY"]})
with urllib.request.urlopen(req, timeout=60) as r:
    print("trigger:", r.status, r.read().decode()[:400], flush=True)
INGESTEOF

# ── status: scoped by workspace_id, NOT project_id. silver.document_passages
#    has no project_id column at all — it reaches a project only through
#    document_id -> silver.reports. embedding_id is the embedded marker; there
#    is no embedded_at. ───────────────────────────────────────────────────────
read -r -d '' STATUS_PY <<'STATUSEOF' || true
import asyncio
import asyncpg
from app.db.dsn import build_dsn

WID = "${WID}"

async def main():
    conn = await asyncpg.connect(build_dsn(scheme="postgresql", include_sslmode=True))
    try:
        await conn.execute("SELECT set_config(\$1,\$2,false)", "app.workspace_id", WID)
        row = await conn.fetchrow(
            "SELECT count(*) AS n, count(embedding_id) AS e "
            "FROM silver.document_passages WHERE workspace_id::text = \$1", WID)
    finally:
        await conn.close()
    print(f"passages={row['n']} embedded={row['e']}", flush=True)
    if row["e"]:
        print("READY - run: bash step5.sh query", flush=True)
    elif row["n"]:
        print("NOT READY - passages written, embeddings still running; re-check", flush=True)
    else:
        print("NOT READY - no passages yet. If this stays at 0 for more than a few "
              "minutes the ingest workflow may have FAILED rather than be slow; "
              "check the hatchet-worker log stream in /ecs/georag.", flush=True)

asyncio.run(main())
STATUSEOF

case "\$ACTION" in
  ingest)
    # Checked BEFORE seeding: discovering the PDF is missing after the seed has
    # already run wastes a task and leaves the corpus half-set-up.
    PDF="\${PDF:-./PLS-2024-Technical-Report.pdf}"
    if [ ! -f "\$PDF" ]; then
      echo "PDF not found: \$PDF" >&2
      echo "Upload it via CloudShell Actions -> Upload file, or set PDF=/path/to/file.pdf." >&2
      echo "It is NOT in the container image: docker/fastapi.Dockerfile.dockerignore" >&2
      echo "excludes **/tests/fixtures, so the fixture never reaches the build context." >&2
      exit 1
    fi

    echo "=== 1/2  seed the two-tenant corpus ============================="
    OVR=\$(jq -n --arg py "\$SEED_PY" '{containerOverrides:[{name:"fastapi",command:["python3","-c",\$py]}]}')
    CODE=\$(run_task seed "\$OVR")
    echo "seed exit: \$CODE"
    # Stop here on failure: firing the trigger at a project that does not exist
    # returns 403 from require_active_project, which reads like a permissions
    # problem rather than a missing row — a bad five minutes for whoever hits it.
    [ "\$CODE" = "0" ] || { echo "SEED FAILED - not running ingest"; exit 1; }

    echo
    echo "=== 2/2  upload the PDF and trigger ingest_pdf =================="
    # The bucket name is read from the deployed task definition rather than
    # hardcoded: AWS_BUCKET_BRONZE lives in common_environment
    # (deploy/aws/terraform/config.tf) and this way the bundle cannot drift
    # from what the services actually use.
    BUCKET=\$(aws ecs describe-task-definition --task-definition georag-fastapi \\
      --query 'taskDefinition.containerDefinitions[0].environment[?name==\`AWS_BUCKET_BRONZE\`].value | [0]' \\
      --output text)
    if [ -z "\$BUCKET" ] || [ "\$BUCKET" = "None" ]; then
      echo "could not read AWS_BUCKET_BRONZE from the georag-fastapi task definition" >&2
      exit 1
    fi
    KEY="reports/\$PID/rehearsal-\$(date +%s)-\$\$.pdf"
    SIZE=\$(stat -c%s "\$PDF")
    echo "uploading \$PDF (\$SIZE bytes) -> s3://\$BUCKET/\$KEY"
    aws s3 cp "\$PDF" "s3://\$BUCKET/\$KEY" >/dev/null || { echo "UPLOAD FAILED"; exit 1; }

    OVR=\$(jq -n --arg py "\$INGEST_PY" --arg k "\$KEY" --arg s "\$SIZE" '{
      containerOverrides:[{
        name:"fastapi",
        command:["python3","-c",\$py],
        environment:[{name:"REHEARSAL_S3_KEY",value:\$k},
                     {name:"REHEARSAL_FILE_SIZE",value:\$s}]}]}')
    CODE=\$(run_task ingest "\$OVR")
    echo "ingest exit: \$CODE"
    [ "\$CODE" = "0" ] || { echo "INGEST DISPATCH FAILED"; exit 1; }
    echo
    echo "Ingestion DISPATCHED. 202 means Hatchet ACCEPTED the run, not that it"
    echo "finished - it now parses / chunks / embeds / indexes for some minutes."
    echo "Poll with: bash step5.sh status"
    ;;

  status)
    OVR=\$(jq -n --arg py "\$STATUS_PY" '{containerOverrides:[{name:"fastapi",command:["python3","-c",\$py]}]}')
    CODE=\$(run_task status "\$OVR")
    echo "status exit: \$CODE"
    ;;

  query)
    # step5_answer_path.py lives IN the image (src/fastapi/scripts/ops/), so
    # only its environment travels. It asserts four things: HTTP 200; at least
    # two delta frames; \`completed\` is the LAST frame; and a citation carrying
    # a non-null source_chunk_id that RESOLVES to a real chunk in Qdrant.
    OVR=\$(jq -n --arg pid "\$PID" --arg wid "\$WID" --arg q "\$QUESTION" '{
      containerOverrides: [{
        name: "fastapi",
        command: ["python3","/app/scripts/ops/step5_answer_path.py"],
        environment: [
          {name:"PROD_SMOKE_PROJECT_ID",   value:\$pid},
          {name:"PROD_SMOKE_WORKSPACE_ID", value:\$wid},
          {name:"REHEARSAL_QUESTION",      value:\$q}
        ]}]}')
    CODE=\$(run_task step5 "\$OVR")
    echo "exit code: \$CODE"
    [ "\$CODE" = "0" ] || { echo "STEP 5 FAILED"; exit 1; }
    echo "STEP 5 OK - the answer streamed, cited a real chunk, and terminated cleanly."
    ;;

  *) echo "usage: bash step5.sh {ingest|status|query}" >&2; exit 2 ;;
esac
BUNDLE
