"""Pydantic models for silver.message_feedback — Module 7 Phase B Chunk 1.

FeedbackCreate is the POST body; FeedbackRead is the response after INSERT.
Both mirror the DB CHECK constraints exactly.

Taxonomy (§10p from module spec):
  'hallucinated'   — model invented / fabricated facts
  'wrong_facts'    — factually incorrect but plausible
  'missing_info'   — incomplete answer / omitted relevant context
  'off_topic'      — answer not relevant to the question
  'citation_issue' — wrong, missing, or mis-matched citations
  'length_issue'   — answer too long or too short

Polarity:
  'up'   — positive; category is optional (nullable in DB)
  'down' — negative; category is required (CHECK constraint + model_validator)

Multiple feedback rows per user per answer_run are allowed.  The UI renders
the latest row (ORDER BY created_at DESC LIMIT 1) as the current user stance.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field, model_validator

# ---------------------------------------------------------------------------
# Literal types — mirror DB CHECK constraints exactly
# ---------------------------------------------------------------------------

FeedbackPolarity = Literal["up", "down"]

FeedbackCategory = Literal[
    "hallucinated",   # model invented / fabricated facts
    "wrong_facts",    # factually incorrect
    "missing_info",   # incomplete / missing needed context
    "off_topic",      # not relevant to question
    "citation_issue", # wrong/missing citations
    "length_issue",   # too long or too short
]


# ---------------------------------------------------------------------------
# FeedbackCreate — POST body
# ---------------------------------------------------------------------------


class FeedbackCreate(BaseModel):
    """Request body for POST /v1/answer_runs/{id}/feedback.

    Pydantic enforces the same constraint as the DB:
      - polarity='down' requires a category from the 6-value taxonomy.
      - polarity='up' leaves category optional (None is persisted as NULL).
      - note is free-form text capped at 2000 characters.
    """

    polarity: FeedbackPolarity
    category: FeedbackCategory | None = None
    note: str | None = Field(None, max_length=2000)

    @model_validator(mode="after")
    def require_category_when_down(self) -> FeedbackCreate:
        """Mirror the DB CHECK message_feedback_category_required_when_down.

        Raises ValueError (becomes HTTP 422 from FastAPI) if polarity is
        'down' and category is None.
        """
        if self.polarity == "down" and self.category is None:
            raise ValueError("category is required when polarity is 'down'")
        return self


# ---------------------------------------------------------------------------
# FeedbackRead — response shape after INSERT
# ---------------------------------------------------------------------------


class FeedbackRead(FeedbackCreate):
    """Full silver.message_feedback row returned after successful INSERT.

    Extends FeedbackCreate with the server-populated fields:
      feedback_id   — UUID generated by the DB (gen_random_uuid())
      answer_run_id — FK to silver.answer_runs
      workspace_id  — FK to silver.workspaces (denormalised for RBAC queries)
      user_id       — FK to public.users.id (None for anonymous)
      created_at    — server-side TIMESTAMPTZ
    """

    feedback_id: UUID
    answer_run_id: UUID
    workspace_id: UUID
    user_id: int | None
    created_at: datetime

    model_config = {"from_attributes": True}
