import { useMemo, useState } from 'react';

/**
 * StereonetCard — server-rendered stereonet PNG with a hoverable / clickable
 * point overlay for the `stereonet` chart-card kind (ADR-0007 PR-2).
 *
 * The PNG is generated by Python's mplstereonet on the FastAPI worker so the
 * projection (default: equal-area Schmidt, lower hemisphere) cannot be
 * synthesised client-side — preserves the §04i citation chain because the
 * LLM never assembles α/β → great-circle math itself.
 *
 * The `points` array carries pre-computed unit-circle coordinates
 * (`stereonet_x`, `stereonet_y` in roughly [-1, 1]) so the React overlay can
 * place interactive dots over the static PNG without re-projecting. Each dot
 * is bound to a `source_row_id` (silver.structure.id) for cite-on-click.
 *
 * Coordinate mapping (CSS Y is flipped vs. math Y):
 *   left = (0.5 + x/2) * 100 %
 *   top  = (0.5 - y/2) * 100 %
 *
 * Empty state: no measurements extracted yet (the PR-2 backend asset
 * `silver_structure_populate` is what fills this).
 */

export interface StereonetPoint {
    depth: number | null;
    structure_type: string;
    strike_deg: number | null;
    dip_deg: number | null;
    dip_direction_deg: number | null;
    plunge_deg: number | null;
    trend_deg: number | null;
    stereonet_x: number;
    stereonet_y: number;
    source_row_id: string;
}

export interface StereonetMeta {
    image_base64: string;
    projection: string;
    structure_count: number;
    points: StereonetPoint[];
}

interface StereonetCardProps {
    meta: StereonetMeta;
    onPointClick?: (sourceRowId: string) => void;
}

function Chip({ children }: { children: React.ReactNode }) {
    return (
        <span className="text-[10px] uppercase tracking-wider font-semibold text-amber-400 bg-amber-950/60 border border-amber-800/60 px-1.5 py-0.5 rounded">
            {children}
        </span>
    );
}

function tooltipFor(p: StereonetPoint): string {
    const parts: string[] = [p.structure_type || 'structure'];

    if (p.strike_deg != null || p.dip_deg != null) {
        const strike = p.strike_deg != null ? `${p.strike_deg.toFixed(0)}°` : '—';
        const dip = p.dip_deg != null ? `${p.dip_deg.toFixed(0)}°` : '—';
        let line = `strike ${strike} / dip ${dip}`;
        if (p.dip_direction_deg != null) {
            line += ` → ${p.dip_direction_deg.toFixed(0)}°`;
        }
        parts.push(line);
    } else if (p.plunge_deg != null || p.trend_deg != null) {
        const plunge = p.plunge_deg != null ? `${p.plunge_deg.toFixed(0)}°` : '—';
        const trend = p.trend_deg != null ? `${p.trend_deg.toFixed(0)}°` : '—';
        parts.push(`plunge ${plunge} / trend ${trend}`);
    }

    parts.push(p.depth != null ? `${p.depth.toFixed(1)}m` : 'no depth');
    parts.push(p.source_row_id.slice(0, 8));

    return parts.join(' · ');
}

export default function StereonetCard({ meta, onPointClick }: StereonetCardProps) {
    const [hoverIdx, setHoverIdx] = useState<number | null>(null);

    const points = meta.points ?? [];
    const projection = meta.projection || 'Schmidt';
    const structureCount = meta.structure_count ?? points.length;

    const pngSrc = useMemo(() => {
        if (!meta.image_base64) return null;
        return `data:image/png;base64,${meta.image_base64}`;
    }, [meta.image_base64]);

    const isEmpty = points.length === 0;

    return (
        <div
            className="w-full h-full flex flex-col bg-gray-950 text-gray-100"
            data-testid="stereonet-card"
        >
            <div
                className="flex items-center gap-2 px-3 py-2 border-b border-gray-800 bg-gray-900/60"
                data-testid="stereonet-chips"
            >
                <Chip>{projection}</Chip>
                <Chip>{structureCount} pts</Chip>
            </div>

            <div className="flex-1 flex items-center justify-center p-3 min-h-0">
                {isEmpty ? (
                    <div
                        className="text-xs text-gray-500 text-center max-w-xs"
                        data-testid="stereonet-empty"
                    >
                        No structural measurements extracted for this project yet — see
                        ADR-0007 PR-2.
                    </div>
                ) : (
                    <div
                        className="relative aspect-square max-h-full max-w-full"
                        data-testid="stereonet-stage"
                    >
                        {pngSrc ? (
                            <img
                                src={pngSrc}
                                alt={`${projection} stereonet projection with ${structureCount} measurements`}
                                className="block max-w-full max-h-full w-full h-full object-contain"
                                data-testid="stereonet-png"
                                draggable={false}
                            />
                        ) : (
                            <div
                                className="absolute inset-0 rounded-full border border-gray-700 bg-gray-900/40"
                                data-testid="stereonet-png-fallback"
                                aria-hidden="true"
                            />
                        )}

                        <div
                            className="absolute inset-0 pointer-events-none"
                            data-testid="stereonet-overlay"
                        >
                            {points.map((p, idx) => {
                                const leftPct = (0.5 + p.stereonet_x / 2) * 100;
                                const topPct = (0.5 - p.stereonet_y / 2) * 100;
                                const inBounds =
                                    leftPct >= 0 && leftPct <= 100 && topPct >= 0 && topPct <= 100;
                                if (!inBounds) return null;

                                const isHovered = hoverIdx === idx;
                                return (
                                    <button
                                        type="button"
                                        key={`${p.source_row_id}-${idx}`}
                                        data-testid={`stereonet-point-${idx}`}
                                        data-source-row-id={p.source_row_id}
                                        aria-label={tooltipFor(p)}
                                        title={tooltipFor(p)}
                                        onMouseEnter={() => setHoverIdx(idx)}
                                        onMouseLeave={() =>
                                            setHoverIdx((cur) => (cur === idx ? null : cur))
                                        }
                                        onFocus={() => setHoverIdx(idx)}
                                        onBlur={() =>
                                            setHoverIdx((cur) => (cur === idx ? null : cur))
                                        }
                                        onClick={() => onPointClick?.(p.source_row_id)}
                                        className={[
                                            'absolute -translate-x-1/2 -translate-y-1/2 rounded-full pointer-events-auto',
                                            'focus:outline-none focus-visible:ring-2 focus-visible:ring-amber-400',
                                            isHovered
                                                ? 'w-3 h-3 bg-amber-300 border border-amber-200 shadow-md'
                                                : 'w-2 h-2 bg-amber-500/90 border border-amber-300/70 hover:bg-amber-300',
                                            'transition-[width,height,background-color]',
                                        ].join(' ')}
                                        style={{ left: `${leftPct}%`, top: `${topPct}%` }}
                                    />
                                );
                            })}

                            {hoverIdx !== null && points[hoverIdx] && (
                                <div
                                    className="absolute left-1/2 bottom-2 -translate-x-1/2 max-w-[90%] px-2 py-1 rounded bg-gray-900/95 border border-gray-700 text-[11px] text-gray-100 pointer-events-none whitespace-nowrap overflow-hidden text-ellipsis"
                                    data-testid="stereonet-tooltip"
                                >
                                    {tooltipFor(points[hoverIdx])}
                                </div>
                            )}
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}
