#!/usr/bin/env sh
# GeoRAG — MinIO Bucket Initialization Script
#
# Runs after the MinIO server starts (typically as a separate init container
# or via the docker-compose entrypoint override on the minio service).
# Creates the two required buckets for the GeoRAG storage architecture.
#
# Buckets:
#   georag-bronze   — immutable raw file archive (Bronze medallion layer).
#                     Files are written once on ingest and never modified.
#                     Source of truth for all re-processing runs.
#   georag-exports  — user-triggered export downloads (Gold layer outputs).
#                     CSV, GeoJSON, GPKG, and PDF exports land here before
#                     being served via pre-signed URL to the Laravel frontend.
#
# Idempotency: mc mb --ignore-existing means the script is safe to re-run.
# It will not error if the bucket already exists.
#
# MinIO Client (mc) alias configuration is read from environment variables
# injected by docker-compose (MINIO_ROOT_USER, MINIO_ROOT_PASSWORD, MINIO_URL).

set -e  # exit immediately on any mc error other than "already exists"

# ============================================================================
# CONFIGURATION (from docker-compose environment)
# ============================================================================

MINIO_ALIAS="${MINIO_ALIAS:-georag}"
MINIO_URL="${MINIO_URL:-http://minio:9000}"
MINIO_ROOT_USER="${MINIO_ROOT_USER:-minioadmin}"
MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:-minioadmin}"

# ============================================================================
# WAIT FOR MINIO TO BE READY
# ============================================================================

# mc commands will fail if MinIO hasn't finished its startup sequence.
# Poll the health endpoint until it returns 200 before proceeding.
# The health endpoint is available without authentication.

echo "Waiting for MinIO to be ready at ${MINIO_URL} ..."

RETRIES=30
DELAY=2

i=0
until mc ready "${MINIO_ALIAS}" > /dev/null 2>&1 || [ "$i" -ge "$RETRIES" ]; do
    # mc ready requires the alias to exist first — fall back to curl for the
    # initial readiness probe before the alias is configured.
    if curl -sf "${MINIO_URL}/minio/health/live" > /dev/null 2>&1; then
        break
    fi
    i=$((i + 1))
    echo "  MinIO not ready yet (attempt ${i}/${RETRIES}) — retrying in ${DELAY}s ..."
    sleep "$DELAY"
done

if [ "$i" -ge "$RETRIES" ]; then
    echo "ERROR: MinIO did not become ready after $((RETRIES * DELAY)) seconds." >&2
    exit 1
fi

echo "MinIO is ready."

# ============================================================================
# CONFIGURE mc ALIAS
# ============================================================================

# Register the MinIO server under a local alias so subsequent mc commands
# can reference it by name rather than full URL + credentials.
# --insecure is not set — TLS is expected in production. Dev uses HTTP and
# mc will warn but proceed when the URL is http://.

echo "Configuring mc alias '${MINIO_ALIAS}' -> ${MINIO_URL} ..."

mc alias set "${MINIO_ALIAS}" \
    "${MINIO_URL}" \
    "${MINIO_ROOT_USER}" \
    "${MINIO_ROOT_PASSWORD}"

# ============================================================================
# CREATE BUCKETS
# ============================================================================

echo "Creating bucket: georag-bronze ..."
# --ignore-existing: silently succeed if the bucket already exists.
# This makes the script idempotent for container restarts.
mc mb --ignore-existing "${MINIO_ALIAS}/georag-bronze"

echo "Creating bucket: georag-exports ..."
mc mb --ignore-existing "${MINIO_ALIAS}/georag-exports"

# workspace-exports — receiver for /workspace_export Hatchet runs.
# Default for WorkspaceExportInput.bucket in
# src/fastapi/app/hatchet_workflows/workspace_export.py. The workflow
# does plain s3.put_object() with no bucket pre-flight, so a missing
# bucket would cascade to NoSuchBucket on every export attempt.
# 2026-06-03 audit — see AUDIT_AND_FIX_REPORT.md Theme J.
echo "Creating bucket: workspace-exports ..."
mc mb --ignore-existing "${MINIO_ALIAS}/workspace-exports"

# ============================================================================
# BUCKET POLICIES
# ============================================================================

# georag-bronze — no public access. All reads go through the application
# layer (FastAPI or Laravel) which generates pre-signed URLs with a short
# TTL. Object Lock is not configured here (requires MinIO Enterprise or
# explicit versioning setup) — immutability is enforced at the application
# layer by never issuing DELETE or overwrite operations on bronze objects.
mc anonymous set none "${MINIO_ALIAS}/georag-bronze"

# georag-exports — no public access. Export files are served via pre-signed
# URLs generated by Laravel with a configurable expiry (default 1 hour).
# Files are cleaned up by a scheduled Dagster job after TTL expiry.
mc anonymous set none "${MINIO_ALIAS}/georag-exports"

# workspace-exports — no public access. Per-workspace snapshots served
# the same way (pre-signed URL with short TTL).
mc anonymous set none "${MINIO_ALIAS}/workspace-exports"

# ============================================================================
# VERIFY
# ============================================================================

echo ""
echo "Bucket initialization complete. Current buckets:"
mc ls "${MINIO_ALIAS}"

echo ""
echo "GeoRAG MinIO setup finished successfully."
