#!/usr/bin/env bash
# =============================================================================
# scripts/phase4_step7_build_rollup.sh
#
# Phase 4 Step 7 — rebuild the cumulative migration rollup.
#
# Phase 7 Step 4 (R-P6-4) — the rollup historically lived at
# `phase0-4-rollup.sql` but auto-picks-up every `phase[0-9]*` dir,
# so the name went stale as Phase 5/6/7 landed. The canonical name
# is now `current-rollup.sql`; `phase0-4-rollup.sql` is kept as a
# back-compat copy with the same content (a "phase frozen at N"
# bundle can be cut later by snapshotting current-rollup.sql).
#
# Re-run this script whenever a new per-phase migration lands so
# both files stay current.
# =============================================================================

set -euo pipefail

REPO="${REPO_ROOT:-/home/georag/projects/georag}"
PRIMARY="$REPO/database/raw/current-rollup.sql"
LEGACY="$REPO/database/raw/phase0-4-rollup.sql"

{
    # Detect the latest phase number to embed in the header — keeps the
    # banner accurate as new phases land without manual edits.
    latest_phase=$(ls -d "$REPO/database/raw"/phase[0-9]* 2>/dev/null \
        | sed -E 's|.*/phase([0-9]+).*|\1|' | sort -n | tail -1)
    cat <<HEADER
-- =============================================================================
-- GeoRAG Phase 0-${latest_phase:-N} Cumulative Rollup — Greenfield bootstrap
--
-- Concatenation of every phase migration file in dependency order. Apply
-- against a FRESH Postgres cluster to bring it to the latest schema in
-- one shot. Already-installed clusters should continue running the
-- per-phase migrations.
--
-- Canonical filename: current-rollup.sql. The phase0-4-rollup.sql
-- alias is maintained for back-compat with Phase 4 tooling.
--
-- Generated by: $(basename "$0")
-- Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
-- =============================================================================
HEADER

    for phase_dir in $(ls -d "$REPO/database/raw"/phase[0-9]* 2>/dev/null | sort -V); do
        # Skip the rollup file itself if a previous build dropped it here.
        [ -d "$phase_dir" ] || continue
        phase=$(basename "$phase_dir")
        # Version-aware sort so 20-layer-b sorts BEFORE 100-audit-verify
        # (lexical sort would put 100 before 20 and break dependency
        # order in phase0).
        for f in $(ls "$phase_dir"/*.sql 2>/dev/null | sort -V); do
            [ -f "$f" ] || continue
            name=$(basename "$f")
            echo
            echo "-- ============================================================"
            echo "-- ${phase}/${name}"
            echo "-- ============================================================"
            cat "$f"
        done
    done
} > "$PRIMARY"

# Maintain the legacy filename as a byte-for-byte copy. cp not symlink
# so the file is visible from both WSL + Windows side mounts.
cp "$PRIMARY" "$LEGACY"

echo "Rollup written: $PRIMARY"
echo "  legacy alias : $LEGACY"
echo "  lines        : $(wc -l < "$PRIMARY")"
echo "  files        : $(grep -c '^-- phase' "$PRIMARY" || true)"
