#!/usr/bin/env bash
# bootstrap-secrets.sh — operator-side SOPS + age bootstrap.
#
# Idempotent. Safe to re-run; will skip steps that are already done.
# See docs/OPERATOR-AFTERNOON.md for the full procedure.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"

AGE_DIR="${HOME}/.config/georag"
OPERATOR_KEY="${AGE_DIR}/age-key.txt"
CI_KEY="${AGE_DIR}/age-key-ci.txt"
SOPS_VERSION="3.9.4"

c_red() { printf '\033[31m%s\033[0m\n' "$*"; }
c_grn() { printf '\033[32m%s\033[0m\n' "$*"; }
c_yel() { printf '\033[33m%s\033[0m\n' "$*"; }
c_blu() { printf '\033[34m%s\033[0m\n' "$*"; }

require_clean_tree() {
  if ! git diff --quiet || ! git diff --cached --quiet; then
    c_red "ERROR: working tree is not clean. Commit or stash before running."
    exit 1
  fi
}

ensure_age() {
  if command -v age >/dev/null 2>&1 && command -v age-keygen >/dev/null 2>&1; then
    c_grn "✓ age installed: $(age --version 2>&1 | head -1)"
    return
  fi
  c_blu "→ Installing age via apt..."
  sudo apt-get update -qq
  sudo apt-get install -y age
  c_grn "✓ age installed"
}

ensure_sops() {
  if command -v sops >/dev/null 2>&1; then
    c_grn "✓ sops installed: $(sops --version | head -1)"
    return
  fi
  c_blu "→ Installing sops ${SOPS_VERSION}..."
  curl -fsSL "https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops_${SOPS_VERSION}_linux_amd64.deb" \
    -o /tmp/sops.deb
  sudo dpkg -i /tmp/sops.deb
  rm -f /tmp/sops.deb
  c_grn "✓ sops installed"
}

generate_key() {
  local path="$1" label="$2"
  if [ -f "$path" ]; then
    c_grn "✓ ${label} key already exists at ${path} (skipping)"
    return
  fi
  mkdir -p "$AGE_DIR"
  chmod 700 "$AGE_DIR"
  c_blu "→ Generating ${label} age key at ${path}"
  age-keygen -o "$path"
  chmod 600 "$path"
  c_grn "✓ ${label} key generated"
}

write_sops_yaml() {
  local op_pub ci_pub
  op_pub=$(age-keygen -y "$OPERATOR_KEY")
  ci_pub=$(age-keygen -y "$CI_KEY")

  if [ -f .sops.yaml ]; then
    if grep -q "$op_pub" .sops.yaml && grep -q "$ci_pub" .sops.yaml; then
      c_grn "✓ .sops.yaml already lists both public keys"
      return
    fi
    c_yel "⚠ .sops.yaml exists but missing one or both public keys; overwriting"
  fi

  cat > .sops.yaml <<EOF
# .sops.yaml — public age recipients allowed to decrypt .env.production.enc.
# Add a new entry per operator or CI runner key.
# Generated by scripts/operator/bootstrap-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
creation_rules:
  - path_regex: \\.env\\.production\\.enc\$
    age: >-
      ${op_pub},
      ${ci_pub}
EOF
  c_grn "✓ .sops.yaml written"
}

prompt_fill_env() {
  if [ -f .env.production.enc ] && [ ! -f .env.production ]; then
    c_grn "✓ .env.production.enc already exists; skipping initial encryption"
    return 1
  fi

  if [ ! -f .env.production ]; then
    cp .env.production.example .env.production
    c_blu "→ Copied .env.production.example to .env.production"
  fi

  c_yel ""
  c_yel "═══════════════════════════════════════════════════════════════════"
  c_yel "  ACTION REQUIRED — fill .env.production"
  c_yel "═══════════════════════════════════════════════════════════════════"
  c_yel ""
  c_yel "Open .env.production in a text editor and replace every"
  c_yel "CHANGE_ME_VAULT_REFERENCE with a real secret."
  c_yel ""
  c_yel "Generation hints:"
  c_yel "  APP_KEY:           docker compose run --rm laravel-octane php artisan key:generate --show"
  c_yel "  Random 32 bytes:   openssl rand -base64 32"
  c_yel ""
  c_yel "Verify these prod-required values:"
  c_yel "  APP_ENV=production"
  c_yel "  APP_DEBUG=false"
  c_yel "  MULTI_TENANT_ENFORCEMENT_ENABLED=true"
  c_yel "  SINGLE_TENANT_MODE=false"
  c_yel ""
  read -rp "Press ENTER when .env.production is filled and saved..."
  return 0
}

verify_prod_values() {
  local errors=0
  for kv in 'APP_ENV=production' 'APP_DEBUG=false' 'MULTI_TENANT_ENFORCEMENT_ENABLED=true' 'SINGLE_TENANT_MODE=false'; do
    if ! grep -qE "^${kv}\$" .env.production; then
      c_red "✗ .env.production missing required line: ${kv}"
      errors=$((errors+1))
    fi
  done
  if grep -q 'CHANGE_ME_VAULT_REFERENCE' .env.production; then
    local n; n=$(grep -c 'CHANGE_ME_VAULT_REFERENCE' .env.production)
    c_red "✗ .env.production still has ${n} unfilled CHANGE_ME_VAULT_REFERENCE placeholders"
    errors=$((errors+1))
  fi
  if [ "$errors" -gt 0 ]; then
    c_red "Fix the errors above and re-run this script. Plaintext .env.production left in place."
    exit 1
  fi
  c_grn "✓ .env.production passes prod-value checks"
}

encrypt_and_clean() {
  c_blu "→ Encrypting .env.production → .env.production.enc"
  sops --encrypt .env.production > .env.production.enc
  if ! head -5 .env.production.enc | grep -q 'sops'; then
    c_red "✗ Encryption produced unexpected output; aborting"
    exit 1
  fi
  shred -u .env.production 2>/dev/null || rm -f .env.production
  c_grn "✓ .env.production.enc written; plaintext destroyed"
}

print_ci_key_warning() {
  c_yel ""
  c_yel "═══════════════════════════════════════════════════════════════════"
  c_yel "  NEXT — store the CI age private key in GitHub Secrets"
  c_yel "═══════════════════════════════════════════════════════════════════"
  c_yel ""
  c_yel "Run scripts/operator/set-github-secrets.sh to upload it."
  c_yel ""
  c_yel "Or, manually:"
  c_yel "  cat ${CI_KEY}"
  c_yel "  Settings → Secrets → Actions → New repository secret"
  c_yel "    Name:  SOPS_AGE_PRIVATE_KEY"
  c_yel "    Value: <full contents incl. AGE-SECRET-KEY-1... line>"
  c_yel ""
  c_yel "STORE BOTH ${OPERATOR_KEY} AND ${CI_KEY}"
  c_yel "IN YOUR PASSWORD MANAGER NOW. They cannot be regenerated."
  c_yel ""
}

main() {
  c_blu "GeoRAG operator bootstrap — SOPS + age"
  c_blu "Repo: ${REPO_ROOT}"
  echo

  require_clean_tree
  ensure_age
  ensure_sops
  generate_key "$OPERATOR_KEY" "operator"
  generate_key "$CI_KEY" "CI"
  write_sops_yaml

  if prompt_fill_env; then
    verify_prod_values
    encrypt_and_clean
  fi

  print_ci_key_warning

  c_grn ""
  c_grn "✓ Bootstrap complete."
  c_grn "  Next: bash scripts/operator/set-github-secrets.sh"
}

main "$@"
